<?php

$dictionary['Expan_Apertura'] = array(

    'table' => 'expan_apertura',
    'audited' => 'true',
    'fields' => array (
        'tipo_apertura' => array(
            'name'=> 'tipo_apertura',
            'vname'=> 'LBL_TIPO_APERTURA',
            'type' => 'enum',
            'len' => '50',
            'options' => 'tipo_apertura_list',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'studio' => 'visible',
            'dependency' => false,
        ),
        
        'provincia_apertura' => array (
            'required' => false,
            'name' => 'provincia_apertura',
            'vname' => 'LBL_PROVINCIA_APERTURA',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '100',
            'size' => '20',
            'options' => 'provincias_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
     
        'abierta' => array (
            'required' => true,
            'name' => 'abierta',
            'vname' => 'LBL_ABIERTA',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '0',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '250',
            'size' => '20',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'localidad_apertura' => 
            array (
                'required' => false,
                'name' => 'localidad_apertura',
                'vname' => 'LBL_LOCALIDAD_APERTURA',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
        ),
        'franquicia' => 
  array (
    'required' => true,
    'name' => 'franquicia',
    'vname' => 'LBL_FRANQUICIA',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'link' => true,
    'options' => 'franquicia_list_todas',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'area_exclusividad' => 
  array (
    'required' => false,
    'name' => 'area_exclusividad',
    'vname' => 'LBL_AREA_EXCLUSIVIDAD',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '300',
    'size'=>'20',
    'studio' => 'visible',
  ),      
  'f_inicio_contrato' => 
  array (
    'required' => false,
    'name' => 'f_inicio_contrato',
    'vname' => 'LBL_FECHA_INICIO_CONTRATO',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  'f_renovacion_contrato' => 
  array (
    'required' => false,
    'name' => 'f_renovacion_contrato',
    'vname' => 'LBL_FECHA_RENOVACION_CONTRATO',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  'f_baja_contrato' => 
  array (
    'required' => false,
    'name' => 'f_baja_contrato',
    'vname' => 'LBL_FECHA_BAJA_CONTRATO',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  
  'motivo_baja' => 
  array (
    'required' => false,
    'name' => 'motivo_baja',
    'vname' => 'LBL_MOTIVO_BAJA',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'link' => true,
    'options' => 'tipo_baja_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'incidencias' => 
  array (
    'required' => false,
    'name' => 'incidencias',
    'vname' => 'LBL_INCIDENCIAS',
    'type' => 'multienum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'incidencias_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'valoracion' => 
  array (
    'required' => false,
    'name' => 'valoracion',
    'vname' => 'LBL_VALORACION_FRAN',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'valoracion_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  
  'num_empleados' =>
  array (
    'name' => 'num_empleados',
    'vname' => 'LBL_NUM_EMPLEADOS',
    'type' => 'int',
    'len' => '30',
    'size' => '20',
    
    'default' => 0,
    'audited' => true,
    'reportable' => false,
    'unified_search' => false,
  ),
  
  'motivos_apertura' => 
  array (
    'required' => false,
    'name' =>'motivos_apertura',
    'vname' => 'LBL_MOTIVOS_APERTURA',
    'type' => 'multienum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'motivos_apertura_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'inversion_inicial' => 
  array (
    'required' => false,
    'name' => 'inversion_inicial',
    'vname' => 'LBL_INVERSION_INICIAL',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',    
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
  ),
  
    ),
    'relationships'=>array (
),
    'optimistic_locking'=>true,
        'unified_search'=>true,
    );
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('Expan_Apertura','Expan_Apertura', array('basic','assignable'));
?>