<?php

$dictionary['Expan_Apertura'] = array(

    'table' => 'expan_apertura',
    'audited' => 'true',
    'fields' => array (
        'tipo_apertura' => array(
            'name'=> 'tipo_apertura',
            'vname'=> 'LBL_TIPO_APERTURA',
            'type' => 'enum',
            'len' => '50',
            'options' => 'tipo_apertura_list',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'studio' => 'visible',
            'dependency' => false,
        ),
        
        'provincia_apertura' => array (
            'required' => false,
            'name' => 'provincia_apertura',
            'vname' => 'LBL_PROVINCIA_APERTURA',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '100',
            'size' => '20',
            'options' => 'provincias_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
     
        'abierta' => array (
            'required' => true,
            'name' => 'abierta',
            'vname' => 'LBL_ABIERTA',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '0',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '250',
            'size' => '20',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'localidad_apertura' => 
            array (
                'required' => false,
                'name' => 'localidad_apertura',
                'vname' => 'LBL_LOCALIDAD_APERTURA',
                'type' => 'varchar',
                'massupdate' => 0,
                'no_default' => false,
                'comments' => '',
                'help' => '',
                'importable' => 'true',
                'duplicate_merge' => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited' => true,
                'reportable' => true,
                'unified_search' => false,
                'merge_filter' => 'disabled',
                'len' => '255',
                'size' => '20',
        ),
        'franquicia' => 
  array (
    'required' => true,
    'name' => 'franquicia',
    'vname' => 'LBL_FRANQUICIA',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'link' => true,
    'options' => 'franquicia_list_todas',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'area_exclusividad' => 
  array (
    'required' => false,
    'name' => 'area_exclusividad',
    'vname' => 'LBL_AREA_EXCLUSIVIDAD',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '300',
    'size'=>'20',
    'studio' => 'visible',
  ),      
  'f_inicio_contrato' => 
  array (
    'required' => false,
    'name' => 'f_inicio_contrato',
    'vname' => 'LBL_FECHA_INICIO_CONTRATO',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  'f_renovacion_contrato' => 
  array (
    'required' => false,
    'name' => 'f_renovacion_contrato',
    'vname' => 'LBL_FECHA_RENOVACION_CONTRATO',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  'f_baja_contrato' => 
  array (
    'required' => false,
    'name' => 'f_baja_contrato',
    'vname' => 'LBL_FECHA_BAJA_CONTRATO',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  
  'motivo_baja' => 
  array (
    'required' => false,
    'name' => 'motivo_baja',
    'vname' => 'LBL_MOTIVO_BAJA',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'link' => true,
    'options' => 'tipo_baja_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'incidencias' => 
  array (
    'required' => false,
    'name' => 'incidencias',
    'vname' => 'LBL_INCIDENCIAS',
    'type' => 'multienum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'incidencias_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'valoracion' => 
  array (
    'required' => false,
    'name' => 'valoracion',
    'vname' => 'LBL_VALORACION_FRAN',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'valoracion_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  
  'num_empleados' =>
  array (
    'name' => 'num_empleados',
    'vname' => 'LBL_NUM_EMPLEADOS',
    'type' => 'int',
    'len' => '30',
    'size' => '20',
    
    'default' => 0,
    'audited' => true,
    'reportable' => false,
    'unified_search' => false,
  ),
  
  'motivos_apertura' => 
  array (
    'required' => false,
    'name' =>'motivos_apertura',
    'vname' => 'LBL_MOTIVOS_APERTURA',
    'type' => 'multienum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'motivos_apertura_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'inversion_inicial' => 
  array (
    'required' => false,
    'name' => 'inversion_inicial',
    'vname' => 'LBL_INVERSION_INICIAL',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',    
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
  ),
  
  
   'f_precontrato_firma' => 
  array (
    'required' => false,
    'name' => 'f_inicio_contrato',
    'vname' => 'LBL_FECHA_PRECONTRATO_FIRMA',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  
  'pre_fir1_first_name' =>
    array (
        'name' => 'pre_fir1_first_name',
        'vname' => 'LBL_FIRST_NAME',
        'type' => 'varchar',
        'len' => '100',
        'unified_search' => true,
        'full_text_search' => array('boost' => 3),
        'comment' => 'Nombre del primer firmante del precontrato',
        'merge_filter' => 'selected',                
    ),
  
    'pre_fir1_last_name' =>
    array (
        'name' => 'pre_fir1_last_name',
        'vname' => 'LBL_LAST_NAME',
        'type' => 'varchar',
        'len' => '100',
        'unified_search' => true,
        'full_text_search' => array('boost' => 3),
        'comment' => 'Apellidos del primer firmante del precontrato',
        'merge_filter' => 'selected',                
    ),
    
   'pre_fir1_NIF' =>
    array (
        'name' => 'pre_fir1_NIF',
        'vname' => 'LBL_NIF',
        'type' => 'varchar',
        'len' => '20',
        'unified_search' => true,
        'full_text_search' => array('boost' => 3),
        'comment' => 'Nif del primer firmante del precontrato',
        'merge_filter' => 'selected',                
    ),
    
   'pre_fir1_vecino' =>
    array (
        'name' => 'pre_fir1_vecino',
        'vname' => 'LBL_VECINO',
        'type' => 'varchar',
        'len' => '100',
        'comment' => 'Vecino de: del primer firmante del precontrato',
        'merge_filter' => 'selected',                
    ),
  
    'pre_fir1_domicilio' =>
    array (
        'name' => 'pre_fir1_domicilio',
        'vname' => 'LBL_DOMICILIO',
        'type' => 'varchar',
        'len' => '200',
        'comment' => 'Domicilio del primer firmante del precontrato',
        'merge_filter' => 'selected',                
    ),
  
    'pre_fir2_first_name' =>
    array (
        'name' => 'pre_fir2_first_name',
        'vname' => 'LBL_FIRST_NAME',
        'type' => 'varchar',
        'len' => '100',
        'unified_search' => true,
        'full_text_search' => array('boost' => 3),
        'comment' => 'Nombre del segundo firmante del precontrato',
        'merge_filter' => 'selected',                
    ),
  
    'pre_fir2_last_name' =>
    array (
        'name' => 'pre_fir2_last_name',
        'vname' => 'LBL_LAST_NAME',
        'type' => 'varchar',
        'len' => '100',
        'unified_search' => true,
        'full_text_search' => array('boost' => 3),
        'comment' => 'Apellidos del segundo firmante del precontrato',
        'merge_filter' => 'selected',                
    ),
  
   'pre_fir2_NIF' =>
    array (
        'name' => 'pre_fir2_NIF',
        'vname' => 'LBL_NIF',
        'type' => 'varchar',
        'len' => '20',
        'unified_search' => true,
        'full_text_search' => array('boost' => 3),
        'comment' => 'Nif del segundo firmante del precontrato',
        'merge_filter' => 'selected',                
    ),
    
   'pre_fir2_vecino' =>
    array (
        'name' => 'pre_fir2_vecino',
        'vname' => 'LBL_VECINO',
        'type' => 'varchar',
        'len' => '100',
        'comment' => 'Vecino de: del segundo firmante del precontrato',
        'merge_filter' => 'selected',                
    ),
  
    'pre_fir2_domicilio' =>
    array (
        'name' => 'pre_fir2_domicilio',
        'vname' => 'LBL_DOMICILIO',
        'type' => 'varchar',
        'len' => '100',
        'comment' => 'Domicilio del segundo firmante del precontrato',
        'merge_filter' => 'selected',                
    ),
  
      'pre_num_unidades' =>
      array (
        'name' => 'num_empleados',
        'vname' => 'LBL_PRE_NUM_UNIDADES',
        'type' => 'int',
        'len' => '10',
        'size' => '10',
        'comment' => 'Numero de unidade de negocio a adquirir',
        'default' => null,
        'audited' => true,
        'reportable' => false,
        'unified_search' => false,
      ),
  
      'provincia_apertura' => 
      array (
        'required' => false,
        'name' => 'provincia_apertura',
        'vname' => 'LBL_PROVINCIA_APERTURA',
        'type' => 'enum',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => 100,
        'size' => '20',
        'options' => 'provincias_list',
        'studio' => 'visible',
        'dependency' => false,
      ),
      
      'localidad_apertura' => 
      array (
        'required' => false,
        'name' => 'localidad_apertura',
        'vname' => 'LBL_LOCALIDAD_APERTURA',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
      ),
      
   'periodo_validez' =>
    array (
        'name' => 'periodo_validez',
        'vname' => 'LBL_PERIODO_VALIDEZ',
        'type' => 'varchar',
        'len' => '100',
        'comment' => 'Periodo de validez',
        'merge_filter' => 'selected',                
    ),
    
   'entrega_cuenta' =>
    array (
        'name' => 'entrega_cuenta',
        'vname' => 'LBL_ENTREGA_CUENTA',
        'type' => 'varchar',
        'len' => '100',
        'comment' => 'Entrega a cuenta al firmar el precontrato',
        'merge_filter' => 'selected',                
    ),
  
     'canon_entrada' =>
    array (
        'name' => 'canon_entrada',
        'vname' => 'LBL_CANON_ENTRADA',
        'type' => 'varchar',
        'len' => '100',
        'comment' => 'Canon de entrada',
        'merge_filter' => 'selected',                
    ),
  
  'f_contrato_firma' => 
  array (
    'required' => false,
    'name' => 'f_inicio_contrato',
    'vname' => 'LBL_FECHA_CONTRATO_FIRMA',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  
  'con_fir1_first_name' =>
    array (
        'name' => 'con_fir1_first_name',
        'vname' => 'LBL_FIRST_NAME',
        'type' => 'varchar',
        'len' => '100',
        'unified_search' => true,
        'full_text_search' => array('boost' => 3),
        'comment' => 'Nombre del primer firmante del contrato',
        'merge_filter' => 'selected',                
    ),
  
    'con_fir1_last_name' =>
    array (
        'name' => 'con_fir1_last_name',
        'vname' => 'LBL_LAST_NAME',
        'type' => 'varchar',
        'len' => '100',
        'unified_search' => true,
        'full_text_search' => array('boost' => 3),
        'comment' => 'Apellidos del primer firmante del contrato',
        'merge_filter' => 'selected',                
    ),
    
   'con_fir1_NIF' =>
    array (
        'name' => 'con_fir1_NIF',
        'vname' => 'LBL_NIF',
        'type' => 'varchar',
        'len' => '100',
        'unified_search' => true,
        'full_text_search' => array('boost' => 3),
        'comment' => 'Nif del primer firmante del contrato',
        'merge_filter' => 'selected',                
    ),
    
   'con_fir1_vecino' =>
    array (
        'name' => 'con_fir1_vecino',
        'vname' => 'LBL_VECINO',
        'type' => 'varchar',
        'len' => '100',
        'comment' => 'Vecino de: del primer firmante del contrato',
        'merge_filter' => 'selected',                
    ),
  
    'con_fir1_domicilio' =>
    array (
        'name' => 'con_fir1_domicilio',
        'vname' => 'LBL_DOMICILIO',
        'type' => 'varchar',
        'len' => '100',
        'comment' => 'Domicilio del primer firmante del contrato',
        'merge_filter' => 'selected',                
    ),
  
    'con_fir2_first_name' =>
    array (
        'name' => 'con_fir2_first_name',
        'vname' => 'LBL_FIRST_NAME',
        'type' => 'varchar',
        'len' => '100',
        'unified_search' => true,
        'full_text_search' => array('boost' => 3),
        'comment' => 'Nombre del segundo firmante del contrato',
        'merge_filter' => 'selected',                
    ),
  
    'con_fir2_last_name' =>
    array (
        'name' => 'con_fir2_last_name',
        'vname' => 'LBL_LAST_NAME',
        'type' => 'varchar',
        'len' => '100',
        'unified_search' => true,
        'full_text_search' => array('boost' => 3),
        'comment' => 'Apellidos del segundo firmante del contrato',
        'merge_filter' => 'selected',                
    ),
  
   'con_fir2_NIF' =>
    array (
        'name' => 'con_fir2_NIF',
        'vname' => 'LBL_NIF',
        'type' => 'varchar',
        'len' => '100',
        'unified_search' => true,
        'full_text_search' => array('boost' => 3),
        'comment' => 'Nif del segundo firmante del contrato',
        'merge_filter' => 'selected',                
    ),
    
   'con_fir2_vecino' =>
    array (
        'name' => 'con_fir2_vecino',
        'vname' => 'LBL_VECINO',
        'type' => 'varchar',
        'len' => '200',
        'comment' => 'Vecino de: del segundo firmante del contrato',
        'merge_filter' => 'selected',                
    ),
  
    'con_fir2_domicilio' =>
    array (
        'name' => 'con_fir2_domicilio',
        'vname' => 'LBL_DOMICILIO',
        'type' => 'varchar',
        'len' => '200',
        'comment' => 'Domicilio del segundo firmante del contrato',
        'merge_filter' => 'selected',                
    ),
  
  
      'sociedad1_localidad' => 
      array (
        'required' => false,
        'name' => 'sociedad1_localidad',
        'vname' => 'LBL_LOCALIDAD',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
      ),
  
      'sociedad2_localidad' => 
      array (
        'required' => false,
        'name' => 'sociedad2_localidad',
        'vname' => 'LBL_LOCALIDAD',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
      ),
  
     'sociedad1_provincia' => 
      array (
        'required' => false,
        'name' => 'sociedad1_provincia',
        'vname' => 'LBL_PROVINCIA',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
      'sociedad2_provincia' => 
      array (
        'required' => false,
        'name' => 'sociedad2_provincia',
        'vname' => 'LBL_PROVINCIA',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
      'sociedad1_CP' => 
      array (
        'required' => false,
        'name' => 'sociedad1_CP',
        'vname' => 'LBL_CP',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '10',
        'size' => '10',
      ),
    
      'sociedad2_CP' => 
      array (
        'required' => false,
        'name' => 'sociedad2_CP',
        'vname' => 'LBL_CP',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '10',
        'size' => '10',
      ),
      
      
      'sociedad1_tomo' => 
      array (
        'required' => false,
        'name' => 'sociedad1_tomo',
        'vname' => 'LBL_TOMO',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '10',
        'size' => '10',
      ),
   
      'sociedad2_tomo' => 
      array (
        'required' => false,
        'name' => 'sociedad2_tomo',
        'vname' => 'LBL_TOMO',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '10',
        'size' => '10',
      ),
      
      'sociedad1_hoja' => 
      array (
        'required' => false,
        'name' => 'sociedad1_hoja',
        'vname' => 'LBL_HOJA',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '10',
        'size' => '10',
      ),
      
     'sociedad2_hoja' => 
      array (
        'required' => false,
        'name' => 'sociedad2_hoja',
        'vname' => 'LBL_HOJA',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '10',
        'size' => '10',
      ),
      
      'sociedad1_folio' => 
      array (
        'required' => false,
        'name' => 'sociedad1_folio',
        'vname' => 'LBL_FOLIO',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '10',
        'size' => '10',
      ),
      
     'sociedad2_folio' => 
      array (
        'required' => false,
        'name' => 'sociedad2_folio',
        'vname' => 'LBL_FOLIO',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '10',
        'size' => '10',
      ),
      
      'sociedad1_inscripcion' => 
      array (
        'required' => false,
        'name' => 'sociedad1_inscripcion',
        'vname' => 'LBL_INSCRIPCION',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '10',
        'size' => '10',
      ),
      
      'sociedad2_inscripcion' => 
      array (
        'required' => false,
        'name' => 'sociedad2_inscripcion',
        'vname' => 'LBL_INSCRIPCION',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '10',
        'size' => '10',
      ),

     'local_municipio' => 
      array (
        'required' => false,
        'name' => 'local_municipio',
        'vname' => 'LBL_MUNICIPIO',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),           
  
     'local_provincia' => 
      array (
        'required' => false,
        'name' => 'local_provincia',
        'vname' => 'LBL_PROVINCIA',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
      'local_CP' => 
      array (
        'required' => false,
        'name' => 'local_CP',
        'vname' => 'LBL_CP',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '10',
        'size' => '10',
      ),
  
      'local_Direccion' => 
      array (
        'required' => false,
        'name' => 'local1_Direccion',
        'vname' => 'LBL_DIRECCION',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '200',
        'size' => '10',
      ),
      
      'f_tope_apertura' => 
      array (
        'required' => false,
        'name' => 'f_inicio_contrato',
        'vname' => 'LBL_FECHA_INICIO_CONTRATO',
        'type' => 'date',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'size' => '20',
        'enable_range_search' => false,
      ),
      
      'n_cuenta' => 
      array (
        'required' => false,
        'name' => 'n_cuenta',
        'vname' => 'LBL_CUENTA',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
            
      'duracion_contrato' => 
      array (
        'required' => false,
        'name' => 'duracion_contrato',
        'vname' => 'LBL_DURACION_CONTRATO',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '50',
        'size' => '20',
      ),
      
      'canon_entrada_definitivo' => 
      array (
        'required' => false,
        'name' => 'canon_entrada_definitivo',
        'vname' => 'LBL_CANON_ENTRADA',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '50',
        'size' => '20',
        
      ),
      
      'zona_exlusividad' => 
      array (
        'required' => false,
        'name' => 'zona_exlusividad',
        'vname' => 'LBL_ZONA_EXCLUSIVIDAD',
        'type' => 'text',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'size' => '20',
        'studio' => 'visible',
        'rows' => '4',
        'cols' => '40',
      ),
      
      'Comision_cons_cartera' => 
      array (
            'required' => true,
            'name' => 'Comision_cons_cartera',
            'vname' => 'LBL_COMISION_CONS_CARTERA',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '0',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '250',
            'size' => '20',
            'studio' => 'visible',
            'dependency' => false,
       ),
      
      
      'f_ini_com_cons_cartera' => 
      array (
        'required' => false,
        'name' => 'f_ini_com_cons_cartera',
        'vname' => 'LBL_FECHA_INI_COM_CONS_CARTERA',
        'type' => 'date',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'size' => '20',
        'enable_range_search' => false,
      ),
            
      'f_fin_com_cons_cartera' => 
      array (
        'required' => false,
        'name' => 'f_fin_com_cons_cartera',
        'vname' => 'LBL_FECHA_FIN_COM_CONS_CARTERA',
        'type' => 'date',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'size' => '20',
        'enable_range_search' => false,
      ),     
      
      'proy_ERM' => array(
        'name'=> 'proy_ERM',
        'vname'=> 'LBL_PROY_ERM',
        'type' => 'enum',
        'len' => '50',
        'options' => 'proy_ERM_list',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'studio' => 'visible',
        'dependency' => false,
      ),
          
  
    ),
    'relationships'=>array (
),
    'optimistic_locking'=>true,
        'unified_search'=>true,
    );
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('Expan_Apertura','Expan_Apertura', array('basic','assignable'));
?>