<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'Expan',
  'author' => 'ExpandeNegocio',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'ExpandeFran',
  'published_date' => '2014-08-16 22:21:21',
  'type' => 'module',
  'version' => 1408227681,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'ExpandeFran',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'Expan_Evento',
      'class' => 'Expan_Evento',
      'path' => 'modules/Expan_Evento/Expan_Evento.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'Expan_Solicitud',
      'class' => 'Expan_Solicitud',
      'path' => 'modules/Expan_Solicitud/Expan_Solicitud.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'Expan_Franquicia',
      'class' => 'Expan_Franquicia',
      'path' => 'modules/Expan_Franquicia/Expan_Franquicia.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'Expan_Documentacion',
      'class' => 'Expan_Documentacion',
      'path' => 'modules/Expan_Documentacion/Expan_Documentacion.php',
      'tab' => true,
    ),
    4 => 
    array (
      'module' => 'Expan_GestionSolicitudes',
      'class' => 'Expan_GestionSolicitudes',
      'path' => 'modules/Expan_GestionSolicitudes/Expan_GestionSolicitudes.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/expan_solicitud_calls_Expan_Solicitud.php',
      'to_module' => 'Expan_Solicitud',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/expan_solicitud_meetings_Expan_Solicitud.php',
      'to_module' => 'Expan_Solicitud',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/expan_solicitud_tasks_Expan_Solicitud.php',
      'to_module' => 'Expan_Solicitud',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/expan_franquicia_expan_evento_Expan_Evento.php',
      'to_module' => 'Expan_Evento',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/expan_franquicia_expan_evento_Expan_Franquicia.php',
      'to_module' => 'Expan_Franquicia',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/expan_franquicia_expan_documentacion_Expan_Franquicia.php',
      'to_module' => 'Expan_Franquicia',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/expan_solicitud_callsMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/expan_solicitud_meetingsMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/expan_solicitud_tasksMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/expan_franquicia_expan_eventoMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/expan_franquicia_expan_documentacionMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Expan_Evento',
      'to' => 'modules/Expan_Evento',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Expan_Solicitud',
      'to' => 'modules/Expan_Solicitud',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Expan_Franquicia',
      'to' => 'modules/Expan_Franquicia',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Expan_Documentacion',
      'to' => 'modules/Expan_Documentacion',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Expan_GestionSolicitudes',
      'to' => 'modules/Expan_GestionSolicitudes',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Calls.php',
      'to_module' => 'Calls',
      'language' => 'es_ES',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Expan_Solicitud.php',
      'to_module' => 'Expan_Solicitud',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Expan_Solicitud.php',
      'to_module' => 'Expan_Solicitud',
      'language' => 'es_ES',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'es_ES',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Expan_Solicitud.php',
      'to_module' => 'Expan_Solicitud',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Expan_Solicitud.php',
      'to_module' => 'Expan_Solicitud',
      'language' => 'es_ES',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'en_us',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'es_ES',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Expan_Solicitud.php',
      'to_module' => 'Expan_Solicitud',
      'language' => 'en_us',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Expan_Solicitud.php',
      'to_module' => 'Expan_Solicitud',
      'language' => 'es_ES',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Expan_Evento.php',
      'to_module' => 'Expan_Evento',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Expan_Evento.php',
      'to_module' => 'Expan_Evento',
      'language' => 'es_ES',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Expan_Franquicia.php',
      'to_module' => 'Expan_Franquicia',
      'language' => 'en_us',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Expan_Franquicia.php',
      'to_module' => 'Expan_Franquicia',
      'language' => 'es_ES',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Expan_Documentacion.php',
      'to_module' => 'Expan_Documentacion',
      'language' => 'en_us',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Expan_Documentacion.php',
      'to_module' => 'Expan_Documentacion',
      'language' => 'es_ES',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Expan_Franquicia.php',
      'to_module' => 'Expan_Franquicia',
      'language' => 'en_us',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Expan_Franquicia.php',
      'to_module' => 'Expan_Franquicia',
      'language' => 'es_ES',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_ES.lang.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/expan_solicitud_calls_Calls.php',
      'to_module' => 'Calls',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/expan_solicitud_calls_Expan_Solicitud.php',
      'to_module' => 'Expan_Solicitud',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/expan_solicitud_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/expan_solicitud_meetings_Expan_Solicitud.php',
      'to_module' => 'Expan_Solicitud',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/expan_solicitud_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/expan_solicitud_tasks_Expan_Solicitud.php',
      'to_module' => 'Expan_Solicitud',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/expan_franquicia_expan_evento_Expan_Evento.php',
      'to_module' => 'Expan_Evento',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/expan_franquicia_expan_evento_Expan_Franquicia.php',
      'to_module' => 'Expan_Franquicia',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/expan_franquicia_expan_documentacion_Expan_Documentacion.php',
      'to_module' => 'Expan_Documentacion',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/expan_franquicia_expan_documentacion_Expan_Franquicia.php',
      'to_module' => 'Expan_Franquicia',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
        'Calls' => 'expan_solicitud_calls_name',
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
        'Meetings' => 'expan_solicitud_meetings_name',
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
        'Tasks' => 'expan_solicitud_tasks_name',
      ),
    ),
    3 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);