<?PHP
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN Expan_Franquicia
 */

require_once('include/SugarObjects/templates/company/Company.php');

class Expan_Franquicia_sugar extends Company {
	var $new_schema = true;
	var $module_dir = 'Expan_Franquicia';
	var $object_name = 'Expan_Franquicia';
	var $table_name = 'expan_franquicia';
	var $importable = true;
	var $disable_row_level_security = true ; // to ensure that modules created and deployed under CE will continue to function under team security if the instance is upgraded to PRO
		var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
		var $expan_franquicia_type;
		var $industry;
		var $annual_revenue;
		var $phone_fax;
		var $billing_address_street;
		var $billing_address_street_2;
		var $billing_address_street_3;
		var $billing_address_street_4;
		var $billing_address_city;
		var $billing_address_state;
		var $billing_address_postalcode;
		var $billing_address_country;
		var $rating;
		var $phone_office;
		var $phone_alternate;
		var $website;
		var $ownership;
		var $employees;
		var $ticker_symbol;
		var $shipping_address_street;
		var $shipping_address_street_2;
		var $shipping_address_street_3;
		var $shipping_address_street_4;
		var $shipping_address_city;
		var $shipping_address_state;
		var $shipping_address_postalcode;
		var $shipping_address_country;
		var $email1;
		var $email_addresses_primary;
		var $email_addresses;
		var $email_addresses_non_primary;
		var $tipo_ficha;
		var $zona;
		var $logotipo;
		var $video;
		var $exclusion_de_sector;
		var $exclusion_de_subsector;
		var $estado_validacion;
		var $gestionado_por;
		var $tipo_de_franquiciado;
		var $necesario_titulacion;
		var $titulacion;
		var $condiciones_especiales;
		var $fin_condiciones_especiales;
		var $observaciones;
		var $inversion_minima_necesaria;
		var $currency_id;
		var $tipo_franquicia;
		var $necesita_local;
		var $superficie_local;
		var $requisitos_local;
		var $entorno_ubicacion;
		var $observaciones_ubicacion;
		var $provincias_ubicar_negocio;
		var $poblacion_minima;
		var $personal_minimo;
		var $zona_exclisiva;
		var $vigencia_contrato;
		var $reconvertir_negocio;
		var $acuerdo_financiacion;
		var $sector;
		var $breve_descripcion;
		var $centros_nacionales_propios;
		var $centros_nacionales_franquicia;
		var $presencia_internacional;
		var $paises;
		var $red_spain;
		var $centros_extranjeros_propios;
		var $centros_extranjeros_franqui;
		var $red_extrangera;
		var $plantilla_central;
		var $cifra_negocio_grupo;
		var $nifra;
		var $regmarca;
		var $aef;
		var $sellos_calidad;
		var $otro_sello_calidad;
		var $empresa;
		var $locaidad;
		var $direccion_direccion;
		var $direccion_localidad;
		var $direccion_codigo_postal;
		var $direccion_provincia;
		var $direccion_pais;
		var $persona_contacto;
		var $fecha_acuerdo;
		var $fecha_activacion;
		var $ficha_ampliada_anterior;
		var $expan_consultora_id_c;
		var $consultora;
		var $estado_fran;
		var $observaciones_inter;
		var $preseleccionadas;
		var $homologacion;
		var $user_id_c;
		var $ejecutivo_homologacion;
		var $documentacion_pendiente;
		var $objeciones_foros_bbdd;
		var $derecho_entrada_min;
		var $derecho_entrada_max;
		var $royalty_expltacion;
		var $royalty_publicitario;
		var $otros_royalties;
		var $facturacion_year_unidad_fran_1;
		var $facturacion_year_unidad_fran_2;
		var $facturacion_year_unidad_fran_3;
		var $amortizacio_inversion;
		var $beneficio_neto_unidad_fran_1;
		var $beneficio_neto_unidad_fran_2;
		var $beneficio_neto_unidad_fran_3;
		var $tipo_actividad;
		var $movil_general;
		var $cargo_contacto_general;
		var $contacto_administracion;
		var $telefono_administracion;
		var $movil_administracion;
		var $contacto_intermediacion;
		var $telefono_intermediacion;
		var $movil_intermediacion;
		var $correo_administracion;
		var $correo_intermediacion;
		var $correo_general;
		var $contacto_general_2;
		var $telefono_contacto_2;
		var $telefono_alternativo_2;
		var $movil_general_2;
		var $correo_contacto_2;
		var $cargo_contacto_2;
		var $fecha_creacion;
		var $inicio_expansion;
		var $observaciones_administracion;
		var $tipo_cuenta;
		function Expan_Franquicia_sugar(){	
		parent::Company();
	}
	
	function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
}
		
}
?>