<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$dictionary['Expan_Franquicia'] = array(
	'table'=>'expan_franquicia',
	'audited'=>true,
		'duplicate_merge'=>true,
		'fields'=>array (
  'expan_franquicia_type' => 
  array (
    'name' => 'expan_franquicia_type',
    'vname' => 'LBL_TYPE',
    'type' => 'enum',
    'options' => 'expan_franquicia_type_dom',
    'len' => 100,
    'comment' => 'The Company is of this type',
    'required' => false,
    'massupdate' => '1',
    'no_default' => false,
    'comments' => 'The Company is of this type',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'tipo_ficha' => 
  array (
    'required' => false,
    'name' => 'tipo_ficha',
    'vname' => 'LBL_TIPO_FICHA',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'tipo_ficha_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'zona' => 
  array (
    'required' => false,
    'name' => 'zona',
    'vname' => 'LBL_ZONA',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'zona_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'logotipo' => 
  array (
    'required' => false,
    'name' => 'logotipo',
    'vname' => 'LBL_LOGOTIPO',
    'type' => 'image',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 255,
    'size' => '20',
    'studio' => 'visible',
    'dbType' => 'varchar',
    'border' => '',
    'width' => '120',
    'height' => '',
  ),
  'video' => 
  array (
    'required' => false,
    'name' => 'video',
    'vname' => 'LBL_VIDEO',
    'type' => 'url',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
    'gen' => '',
    'link_target' => '_self',
  ),
  'exclusion_de_sector' => 
  array (
    'required' => false,
    'name' => 'exclusion_de_sector',
    'vname' => 'LBL_EXCLUSION_DE_SECTOR',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'exclusion_de_subsector' => 
  array (
    'required' => false,
    'name' => 'exclusion_de_subsector',
    'vname' => 'LBL_EXCLUSION_DE_SUBSECTOR',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'estado_validacion' => 
  array (
    'required' => false,
    'name' => 'estado_validacion',
    'vname' => 'LBL_ESTADO_VALIDACION',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'estado_validacion_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'gestionado_por' => 
  array (
    'required' => false,
    'name' => 'gestionado_por',
    'vname' => 'LBL_GESTIONADO_POR',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '2',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'gestionado_por_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'tipo_de_franquiciado' => 
  array (
    'required' => false,
    'name' => 'tipo_de_franquiciado',
    'vname' => 'LBL_TIPO_DE_FRANQUICIADO',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'tipo_de_franquiciado_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'necesario_titulacion' => 
  array (
    'required' => false,
    'name' => 'necesario_titulacion',
    'vname' => 'LBL_NECESARIO_TITULACION',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'necesario_titulacion_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'titulacion' => 
  array (
    'required' => false,
    'name' => 'titulacion',
    'vname' => 'LBL_TITULACION',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'condiciones_especiales' => 
  array (
    'required' => false,
    'name' => 'condiciones_especiales',
    'vname' => 'LBL_CONDICIONES_ESPECIALES',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '3',
    'cols' => '60',
  ),
  'fin_condiciones_especiales' => 
  array (
    'required' => false,
    'name' => 'fin_condiciones_especiales',
    'vname' => 'LBL_FIN_CONDICIONES_ESPECIALES',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  'observaciones' => 
  array (
    'required' => false,
    'name' => 'observaciones',
    'vname' => 'LBL_OBSERVACIONES',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '3',
    'cols' => '60',
  ),
  'inversion_minima_necesaria' => 
  array (
    'required' => false,
    'name' => 'inversion_minima_necesaria',
    'vname' => 'LBL_INVERSION_MINIMA_NECESARIA',
    'type' => 'currency',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'currency_id' => 
  array (
    'required' => false,
    'name' => 'currency_id',
    'vname' => 'LBL_CURRENCY',
    'type' => 'currency_id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
    'dbType' => 'id',
    'studio' => 'visible',
    'function' => 
    array (
      'name' => 'getCurrencyDropDown',
      'returns' => 'html',
    ),
  ),
  'tipo_franquicia' => 
  array (
    'required' => false,
    'name' => 'tipo_franquicia',
    'vname' => 'LBL_TIPO_FRANQUICIA',
    'type' => 'multienum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'tipo_franquicia_list',
    'studio' => 'visible',
    'isMultiSelect' => true,
  ),
  'necesita_local' => 
  array (
    'required' => false,
    'name' => 'necesita_local',
    'vname' => 'LBL_NECESITA_LOCAL',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'necesita_local_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'superficie_local' => 
  array (
    'required' => false,
    'name' => 'superficie_local',
    'vname' => 'LBL_SUPERFICIE_LOCAL',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'superficie_local_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'requisitos_local' => 
  array (
    'required' => false,
    'name' => 'requisitos_local',
    'vname' => 'LBL_REQUISITOS_LOCAL',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '3',
    'cols' => '60',
  ),
  'entorno_ubicacion' => 
  array (
    'required' => false,
    'name' => 'entorno_ubicacion',
    'vname' => 'LBL_ENTORNO_UBICACION',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'entorno_ubicacion_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'observaciones_ubicacion' => 
  array (
    'required' => false,
    'name' => 'observaciones_ubicacion',
    'vname' => 'LBL_OBSERVACIONES_UBICACION',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '3',
    'cols' => '60',
  ),
  'provincias_ubicar_negocio' => 
  array (
    'required' => false,
    'name' => 'provincias_ubicar_negocio',
    'vname' => 'LBL_PROVINCIAS_UBICAR_NEGOCIO',
    'type' => 'multienum',
    'massupdate' => 0,
    'default' => '^^',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'provincias_list',
    'studio' => 'visible',
    'isMultiSelect' => true,
  ),
  'poblacion_minima' => 
  array (
    'required' => false,
    'name' => 'poblacion_minima',
    'vname' => 'LBL_POBLACION_MINIMA',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'poblacion_minima_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'personal_minimo' => 
  array (
    'required' => false,
    'name' => 'personal_minimo',
    'vname' => 'LBL_PERSONAL_MINIMO',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'personal_minimo_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'zona_exclisiva' => 
  array (
    'required' => false,
    'name' => 'zona_exclisiva',
    'vname' => 'LBL_ZONA_EXCLISIVA',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'booleano_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'vigencia_contrato' => 
  array (
    'required' => false,
    'name' => 'vigencia_contrato',
    'vname' => 'LBL_VIGENCIA_CONTRATO',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '3',
    'cols' => '60',
    'len' => 100,
    'options' => 'vigencia_contrato_list',
    'dependency' => false,
  ),
  'reconvertir_negocio' => 
  array (
    'required' => false,
    'name' => 'reconvertir_negocio',
    'vname' => 'LBL_RECONVERTIR_NEGOCIO',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'booleano_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'acuerdo_financiacion' => 
  array (
    'required' => false,
    'name' => 'acuerdo_financiacion',
    'vname' => 'LBL_ACUERDO_FINANCIACION',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'booleano_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'description' => 
  array (
    'name' => 'description',
    'vname' => 'LBL_DESCRIPTION',
    'type' => 'text',
    'comment' => 'Full text of the note',
    'rows' => '3',
    'cols' => '80',
    'required' => false,
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Full text of the note',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
  ),
  'sector' => 
  array (
    'required' => false,
    'name' => 'sector',
    'vname' => 'LBL_SECTOR',
    'type' => 'multienum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'required' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'lst_sectores',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'breve_descripcion' => 
  array (
    'required' => false,
    'name' => 'breve_descripcion',
    'vname' => 'LBL_BREVE_DESCRIPCION',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '140',
    'size' => '20',
  ),
  'centros_nacionales_propios' => 
  array (
    'required' => false,
    'name' => 'centros_nacionales_propios',
    'vname' => 'LBL_CENTROS_NACIONALES_PROPIOS',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '10',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => 0,
    'max' => false,
    'validation' => 
    array (
      'type' => 'range',
      'min' => 0,
      'max' => false,
    ),
  ),
  'centros_nacionales_franquicia' => 
  array (
    'required' => false,
    'name' => 'centros_nacionales_franquicia',
    'vname' => 'LBL_CENTROS_NACIONALES_FRANQUICIA',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '10',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => 0,
    'max' => false,
    'validation' => 
    array (
      'type' => 'range',
      'min' => 0,
      'max' => false,
    ),
  ),
  'presencia_internacional' => 
  array (
    'required' => false,
    'name' => 'presencia_internacional',
    'vname' => 'LBL_PRESENCIA_INTERNACIONAL',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'booleano_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'paises' => 
  array (
    'required' => false,
    'name' => 'paises',
    'vname' => 'LBL_PAISES',
    'type' => 'multienum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'countries_dom',
    'studio' => 'visible',
    'isMultiSelect' => true,
  ),
  'red_spain' => 
  array (
    'required' => false,
    'name' => 'red_spain',
    'vname' => 'LBL_RED_SPAIN',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '10',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => 0,
    'max' => false,
    'validation' => 
    array (
      'type' => 'range',
      'min' => 0,
      'max' => false,
    ),
  ),
  'centros_extranjeros_propios' => 
  array (
    'required' => false,
    'name' => 'centros_extranjeros_propios',
    'vname' => 'LBL_CENTROS_EXTRANJEROS_PROPIOS',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => 0,
    'max' => false,
    'validation' => 
    array (
      'type' => 'range',
      'min' => 0,
      'max' => false,
    ),
  ),
  'centros_extranjeros_franqui' => 
  array (
    'required' => false,
    'name' => 'centros_extranjeros_franqui',
    'vname' => 'LBL_CENTROS_EXTRANJEROS_FRANQUI',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '10',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => 0,
    'max' => false,
    'validation' => 
    array (
      'type' => 'range',
      'min' => 0,
      'max' => false,
    ),
  ),
  'red_extrangera' => 
  array (
    'required' => false,
    'name' => 'red_extrangera',
    'vname' => 'LBL_RED_EXTRANGERA',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '10',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => 0,
    'max' => false,
    'validation' => 
    array (
      'type' => 'range',
      'min' => 0,
      'max' => false,
    ),
  ),
  'plantilla_central' => 
  array (
    'required' => false,
    'name' => 'plantilla_central',
    'vname' => 'LBL_PLANTILLA_CENTRAL',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '10',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => 0,
    'max' => false,
    'validation' => 
    array (
      'type' => 'range',
      'min' => 0,
      'max' => false,
    ),
  ),
  'cifra_negocio_grupo' => 
  array (
    'required' => false,
    'name' => 'cifra_negocio_grupo',
    'vname' => 'LBL_CIFRA_NEGOCIO_GRUPO',
    'type' => 'currency',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'nifra' => 
  array (
    'required' => false,
    'name' => 'nifra',
    'vname' => 'LBL_NIFRA',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'regmarca' => 
  array (
    'required' => false,
    'name' => 'regmarca',
    'vname' => 'LBL_REGMARCA',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'aef' => 
  array (
    'required' => false,
    'name' => 'aef',
    'vname' => 'LBL_AEF',
    'type' => 'enum',
    'massupdate' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'booleano_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'sellos_calidad' => 
  array (
    'required' => false,
    'name' => 'sellos_calidad',
    'vname' => 'LBL_SELLOS_CALIDAD',
    'type' => 'multienum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'sellos_calidad_list',
    'studio' => 'visible',
    'isMultiSelect' => true,
  ),
  'otro_sello_calidad' => 
  array (
    'required' => false,
    'name' => 'otro_sello_calidad',
    'vname' => 'LBL_OTRO_SELLO_CALIDAD',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'empresa' => 
  array (
    'required' => false,
    'name' => 'empresa',
    'vname' => 'LBL_EMPRESA',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'locaidad' => 
  array (
    'required' => false,
    'name' => 'locaidad',
    'vname' => 'LBL_LOCAIDAD',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'direccion_direccion' => 
  array (
    'required' => false,
    'name' => 'direccion_direccion',
    'vname' => 'LBL_DIRECCION_DIRECCION',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'direccion_localidad' => 
  array (
    'required' => false,
    'name' => 'direccion_localidad',
    'vname' => 'LBL_DIRECCION_LOCALIDAD',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'direccion_codigo_postal' => 
  array (
    'required' => false,
    'name' => 'direccion_codigo_postal',
    'vname' => 'LBL_DIRECCION_CODIGO_POSTAL',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '10',
    'size' => '20',
  ),
  'direccion_provincia' => 
  array (
    'required' => false,
    'name' => 'direccion_provincia',
    'vname' => 'LBL_DIRECCION_PROVINCIA',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'provincias_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'direccion_pais' => 
  array (
    'required' => false,
    'name' => 'direccion_pais',
    'vname' => 'LBL_DIRECCION_PAIS',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'countries_dom',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'persona_contacto' => 
  array (
    'required' => false,
    'name' => 'persona_contacto',
    'vname' => 'LBL_PERSONA_CONTACTO',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'fecha_acuerdo' => 
  array (
    'required' => false,
    'name' => 'fecha_acuerdo',
    'vname' => 'LBL_FECHA_ACUERDO',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  'fecha_activacion' => 
  array (
    'required' => false,
    'name' => 'fecha_activacion',
    'vname' => 'LBL_FECHA_ACTIVACION',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  'ficha_ampliada_anterior' => 
  array (
    'required' => false,
    'name' => 'ficha_ampliada_anterior',
    'vname' => 'LBL_FICHA_AMPLIADA_ANTERIOR',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'expan_consultora_id_c' => 
  array (
    'required' => false,
    'name' => 'expan_consultora_id_c',
    'vname' => 'LBL_CONSULTORA_EXPAN_CONSULTORA_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => true,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'consultora' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'consultora',
    'vname' => 'LBL_CONSULTORA',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'expan_consultora_id_c',
    'ext2' => 'Expan_Consultora',
    'module' => 'Expan_Consultora',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'estado_fran' => 
  array (
    'required' => false,
    'name' => 'estado_fran',
    'vname' => 'LBL_ESTADO_FRAN',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'estado_fran_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'observaciones_inter' => 
  array (
    'required' => false,
    'name' => 'observaciones_inter',
    'vname' => 'LBL_OBSERVACIONES_INTER',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Volcar información relevante de la red',
    'help' => 'Volcar informaci&oacute;n relevante sobre la red.',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '3',
    'cols' => '80',
  ),
  'preseleccionadas' => 
  array (
    'required' => false,
    'name' => 'preseleccionadas',
    'vname' => 'LBL_PRESELECCIONADAS',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'booleano_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'homologacion' => 
  array (
    'required' => false,
    'name' => 'homologacion',
    'vname' => 'LBL_HOMOLOGACION',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'homologacion_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'user_id_c' => 
  array (
    'required' => false,
    'name' => 'user_id_c',
    'vname' => 'LBL_EJECUTIVO_HOMOLOGACION_USER_ID',
    'type' => 'id',
    'massupdate' => 1,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => true,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'ejecutivo_homologacion' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'ejecutivo_homologacion',
    'vname' => 'LBL_EJECUTIVO_HOMOLOGACION',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'user_id_c',
    'ext2' => 'Users',
    'module' => 'Users',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  'documentacion_pendiente' => 
  array (
    'required' => false,
    'name' => 'documentacion_pendiente',
    'vname' => 'LBL_DOCUMENTACION_PENDIENTE',
    'type' => 'multienum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'documentacion_pendiente_list',
    'studio' => 'visible',
    'isMultiSelect' => true,
  ),
  'objeciones_foros_bbdd' => 
  array (
    'required' => false,
    'name' => 'objeciones_foros_bbdd',
    'vname' => 'LBL_OBJECIONES_FOROS_BBDD',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '3',
    'cols' => '80',
  ),
  'derecho_entrada_min' => 
  array (
    'required' => false,
    'name' => 'derecho_entrada_min',
    'vname' => 'LBL_DERECHO_ENTRADA_MIN',
    'type' => 'currency',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'derecho_entrada_max' => 
  array (
    'required' => false,
    'name' => 'derecho_entrada_max',
    'vname' => 'LBL_DERECHO_ENTRADA_MAX',
    'type' => 'currency',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'royalty_expltacion' => 
  array (
    'required' => false,
    'name' => 'royalty_expltacion',
    'vname' => 'LBL_ROYALTY_EXPLTACION',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'royalty_publicitario' => 
  array (
    'required' => false,
    'name' => 'royalty_publicitario',
    'vname' => 'LBL_ROYALTY_PUBLICITARIO',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'otros_royalties' => 
  array (
    'required' => false,
    'name' => 'otros_royalties',
    'vname' => 'LBL_OTROS_ROYALTIES',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'facturacion_year_unidad_fran_1' => 
  array (
    'required' => false,
    'name' => 'facturacion_year_unidad_fran_1',
    'vname' => 'LBL_FACTURACION_YEAR_UNIDAD_FRAN_1',
    'type' => 'currency',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'facturacion_year_unidad_fran_2' => 
  array (
    'required' => false,
    'name' => 'facturacion_year_unidad_fran_2',
    'vname' => 'LBL_FACTURACION_YEAR_UNIDAD_FRAN_2',
    'type' => 'currency',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'facturacion_year_unidad_fran_3' => 
  array (
    'required' => false,
    'name' => 'facturacion_year_unidad_fran_3',
    'vname' => 'LBL_FACTURACION_YEAR_UNIDAD_FRAN_3',
    'type' => 'currency',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'amortizacio_inversion' => 
  array (
    'required' => false,
    'name' => 'amortizacio_inversion',
    'vname' => 'LBL_AMORTIZACIO_INVERSION',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'amortizacio_inversion_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'beneficio_neto_unidad_fran_1' => 
  array (
    'required' => false,
    'name' => 'beneficio_neto_unidad_fran_1',
    'vname' => 'LBL_BENEFICIO_NETO_UNIDAD_FRAN_1',
    'type' => 'currency',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'beneficio_neto_unidad_fran_2' => 
  array (
    'required' => false,
    'name' => 'beneficio_neto_unidad_fran_2',
    'vname' => 'LBL_BENEFICIO_NETO_UNIDAD_FRAN_2',
    'type' => 'currency',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'beneficio_neto_unidad_fran_3' => 
  array (
    'required' => false,
    'name' => 'beneficio_neto_unidad_fran_3',
    'vname' => 'LBL_BENEFICIO_NETO_UNIDAD_FRAN_3',
    'type' => 'currency',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
  ),
  'tipo_actividad' => 
  array (
    'required' => false,
    'name' => 'tipo_actividad',
    'vname' => 'LBL_TIPO_ACTIVIDAD',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'movil_general' => 
  array (
    'required' => false,
    'name' => 'movil_general',
    'vname' => 'LBL_MOVIL_GENERAL',
    'type' => 'phone',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
  ),
  'cargo_contacto_general' => 
  array (
    'required' => false,
    'name' => 'cargo_contacto_general',
    'vname' => 'LBL_CARGO_CONTACTO_GENERAL',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'cargo_contacto_general_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'contacto_administracion' => 
  array (
    'required' => false,
    'name' => 'contacto_administracion',
    'vname' => 'LBL_CONTACTO_ADMINISTRACION',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'telefono_administracion' => 
  array (
    'required' => false,
    'name' => 'telefono_administracion',
    'vname' => 'LBL_TELEFONO_ADMINISTRACION',
    'type' => 'phone',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
  ),
  'movil_administracion' => 
  array (
    'required' => false,
    'name' => 'movil_administracion',
    'vname' => 'LBL_MOVIL_ADMINISTRACION',
    'type' => 'phone',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
  ),
  'contacto_intermediacion' => 
  array (
    'required' => false,
    'name' => 'contacto_intermediacion',
    'vname' => 'LBL_CONTACTO_INTERMEDIACION',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'telefono_intermediacion' => 
  array (
    'required' => false,
    'name' => 'telefono_intermediacion',
    'vname' => 'LBL_TELEFONO_INTERMEDIACION',
    'type' => 'phone',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
  ),
  'movil_intermediacion' => 
  array (
    'required' => false,
    'name' => 'movil_intermediacion',
    'vname' => 'LBL_MOVIL_INTERMEDIACION',
    'type' => 'phone',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
  ),
  'correo_administracion' => 
  array (
    'required' => false,
    'name' => 'correo_administracion',
    'vname' => 'LBL_CORREO_ADMINISTRACION',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'correo_intermediacion' => 
  array (
    'required' => false,
    'name' => 'correo_intermediacion',
    'vname' => 'LBL_CORREO_INTERMEDIACION',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'email1' => 
  array (
    'name' => 'email1',
    'vname' => 'LBL_EMAIL',
    'group' => 'email1',
    'type' => 'varchar',
    'function' => 
    array (
      'name' => 'getEmailAddressWidget',
      'returns' => 'html',
    ),
    'studio' => 
    array (
      'editField' => true,
      'searchview' => false,
    ),
    'full_text_search' => 
    array (
      'boost' => 3,
      'analyzer' => 'whitespace',
    ),
    'required' => false,
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'correo_general' => 
  array (
    'required' => false,
    'name' => 'correo_general',
    'vname' => 'LBL_CORREO_GENERAL',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'contacto_general_2' => 
  array (
    'required' => false,
    'name' => 'contacto_general_2',
    'vname' => 'LBL_CONTACTO_GENERAL_2',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'telefono_contacto_2' => 
  array (
    'required' => false,
    'name' => 'telefono_contacto_2',
    'vname' => 'LBL_TELEFONO_CONTACTO_2',
    'type' => 'phone',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
  ),
  'telefono_alternativo_2' => 
  array (
    'required' => false,
    'name' => 'telefono_alternativo_2',
    'vname' => 'LBL_TELEFONO_ALTERNATIVO_2',
    'type' => 'phone',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'dbType' => 'varchar',
  ),
  'movil_general_2' => 
  array (
    'required' => false,
    'name' => 'movil_general_2',
    'vname' => 'LBL_MOVIL_GENERAL_2',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'correo_contacto_2' => 
  array (
    'required' => false,
    'name' => 'correo_contacto_2',
    'vname' => 'LBL_CORREO_CONTACTO_2',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'cargo_contacto_2' => 
  array (
    'required' => false,
    'name' => 'cargo_contacto_2',
    'vname' => 'LBL_CARGO_CONTACTO_2',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'cargo_contacto_general_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'fecha_creacion' => 
  array (
    'required' => false,
    'name' => 'fecha_creacion',
    'vname' => 'LBL_FECHA_CREACION',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => 1900,
    'max' => 2100,
    'validation' => 
    array (
      'type' => 'range',
      'min' => 1900,
      'max' => 2100,
    ),
  ),
  'inicio_expansion' => 
  array (
    'required' => false,
    'name' => 'inicio_expansion',
    'vname' => 'LBL_INICIO_EXPANSION',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => 1900,
    'max' => 2100,
    'validation' => 
    array (
      'type' => 'range',
      'min' => 1900,
      'max' => 2100,
    ),
  ),
  'observaciones_administracion' => 
  array (
    'required' => false,
    'name' => 'observaciones_administracion',
    'vname' => 'LBL_OBSERVACIONES_ADMINISTRACION',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '80',
  ),
  'tipo_cuenta' => 
  array (
    'required' => true,
    'name' => 'tipo_cuenta',
    'vname' => 'LBL_TIPO_CUENTA',
    'type' => 'enum',
    'massupdate' => '1',
    'default' => '4',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'tipo_cuenta_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'correo_envio' => 
  array (
    'required' => false,
    'name' => 'correo_envio',
    'vname' => 'LBL_CORREO_ENVIO',
    'type' => 'varchar',
    'massupdate' => 1,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
  'chk_c1' => 
  array (
    'required' => false,
    'name' => 'chk_c1',
    'vname' => 'LBL_CHK_C1',
    'type' => 'bool',
    'massupdate' => 1,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'chk_c2' => 
  array (
    'required' => false,
    'name' => 'chk_c2',
    'vname' => 'LBL_CHK_C2',
    'type' => 'bool',
    'massupdate' => 1,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
 
  'chk_c3' => 
  array (
    'required' => false,
    'name' => 'chk_c3',
    'vname' => 'LBL_CHK_C3',
    'type' => 'bool',
    'massupdate' => 1,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
 
    'chk_c4' => 
  array (
    'required' => false,
    'name' => 'chk_c4',
    'vname' => 'LBL_CHK_C4',
    'type' => 'bool',
    'massupdate' => 1,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
      'chk_c11' => 
  array (
    'required' => false,
    'name' => 'chk_c11',
    'vname' => 'LBL_CHK_C11',
    'type' => 'bool',
    'massupdate' => 1,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
        'chk_c12' => 
  array (
    'required' => false,
    'name' => 'chk_c12',
    'vname' => 'LBL_CHK_C12',
    'type' => 'bool',
    'massupdate' => 1,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
        'chk_c13' => 
  array (
    'required' => false,
    'name' => 'chk_c13',
    'vname' => 'LBL_CHK_C13',
    'type' => 'bool',
    'massupdate' => 1,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
        'chk_c14' => 
  array (
    'required' => false,
    'name' => 'chk_c14',
    'vname' => 'LBL_CHK_C14',
    'type' => 'bool',
    'massupdate' => 1,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
        'chk_c15' => 
  array (
    'required' => false,
    'name' => 'chk_c15',
    'vname' => 'LBL_CHK_C15',
    'type' => 'bool',
    'massupdate' => 1,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
   'director_consultoria' => 
    array (
        'labelValue' => 'Director de consultoria',
        'required' => false,
        'source' => 'non-db',
        'name' => 'director_consultoria',
        'vname' => 'LBL_DIRECTOR_CONSULTORIA',
        'type' => 'relate',
        'massupdate' => '0',
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
        'id_name' => 'dir_cons_id_c',
        'ext2' => 'Users',
        'module' => 'Users',
        'rname' => 'name',
        'quicksearch' => 'enabled',
    ),
    
      'dir_cons_id_c' => 
      array (
        'required' => false,
        'name' => 'dir_cons_id_c',
        'vname' => 'LBL_DIRECTOR_CONSULTORIA_USER_ID',
        'type' => 'id',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => 0,
        'audited' => true,
        'reportable' => false,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => 36,
        'size' => '20',
      ),
      
      'llamar_todos' => 
      array (
        'required' => false,
        'name' => 'llamar_todos',
        'vname' => 'LBL_LLAMAR_TODOS',
        'type' => 'bool',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
      ),
      
      'informe_urgente' => 
      array (
        'required' => false,
        'name' => 'informe_urgente',
        'vname' => 'LBL_INFORME_URGENTE',
        'type' => 'enum',
        'massupdate' => 0,
        'default' => '1',
        'no_default' => false,
        'options' => 'tipo_informe_franquicia',
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
      ),
      
      'modNeg1' => 
      array (
        'required' => false,
        'name' => 'modNeg1',
        'vname' => 'LBL_MODNEG1',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
      'valNeg11' => 
      array (
        'required' => false,
        'name' => 'valNeg11',
        'vname' => 'LBL_VALNEG11',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
      'valNeg12' => 
      array (
        'required' => false,
        'name' => 'valNeg12',
        'vname' => 'LBL_VALNEG12',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
     'valNeg13' => 
      array (
        'required' => false,
        'name' => 'valNeg13',
        'vname' => 'LBL_VALNEG13',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
        'valNeg14' => 
      array (
        'required' => false,
        'name' => 'valNeg14',
        'vname' => 'LBL_VALNEG14',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
      'valNeg15' => 
      array (
        'required' => false,
        'name' => 'valNeg15',
        'vname' => 'LBL_VALNEG15',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
    
    'modNeg2' => 
      array (
        'required' => false,
        'name' => 'modNeg2',
        'vname' => 'LBL_MODNEG2',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),  
      
          'valNeg21' => 
      array (
        'required' => false,
        'name' => 'valNeg21',
        'vname' => 'LBL_VALNEG21',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
      'valNeg22' => 
      array (
        'required' => false,
        'name' => 'valNeg22',
        'vname' => 'LBL_VALNEG22',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
     'valNeg23' => 
      array (
        'required' => false,
        'name' => 'valNeg23',
        'vname' => 'LBL_VALNEG23',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
        'valNeg24' => 
      array (
        'required' => false,
        'name' => 'valNeg24',
        'vname' => 'LBL_VALNEG24',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
      'valNeg25' => 
      array (
        'required' => false,
        'name' => 'valNeg25',
        'vname' => 'LBL_VALNEG25',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),  
      
  
    'modNeg3' => 
  array (
    'required' => false,
    'name' => 'modNeg3',
    'vname' => 'LBL_MODNEG3',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '100',
    'size' => '20',
  ),
  
        'valNeg31' => 
      array (
        'required' => false,
        'name' => 'valNeg31',
        'vname' => 'LBL_VALNEG31',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
      'valNeg32' => 
      array (
        'required' => false,
        'name' => 'valNeg32',
        'vname' => 'LBL_VALNEG32',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
     'valNeg33' => 
      array (
        'required' => false,
        'name' => 'valNeg33',
        'vname' => 'LBL_VALNEG33',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
        'valNeg34' => 
      array (
        'required' => false,
        'name' => 'valNeg34',
        'vname' => 'LBL_VALNEG34',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
      'valNeg35' => 
      array (
        'required' => false,
        'name' => 'valNeg35',
        'vname' => 'LBL_VALNEG35',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
    'modNeg4' => 
  array (
    'required' => false,
    'name' => 'modNeg4',
    'vname' => 'LBL_MODNEG4',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '100',
    'size' => '20',
  ),
  
        'valNeg41' => 
      array (
        'required' => false,
        'name' => 'valNeg41',
        'vname' => 'LBL_VALNEG41',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
      'valNeg42' => 
      array (
        'required' => false,
        'name' => 'valNeg42',
        'vname' => 'LBL_VALNEG42',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
     'valNeg43' => 
      array (
        'required' => false,
        'name' => 'valNeg43',
        'vname' => 'LBL_VALNEG43',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
        'valNeg44' => 
      array (
        'required' => false,
        'name' => 'valNeg44',
        'vname' => 'LBL_VALNEG44',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
      
      'valNeg45' => 
      array (
        'required' => false,
        'name' => 'valNeg45',
        'vname' => 'LBL_VALNEG45',
        'type' => 'varchar',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => true,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '100',
        'size' => '20',
      ),
  
  'prioridad' => 
  array (
    'required' => false,
    'name' => 'prioridad',
    'vname' => 'LBL_PRIORIDAD_FRAN',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '100',
    'size' => '20',
  ),
      'gestionesfran' =>
        array(
            'required' => false,
    'name' => 'gestionesfran',
    'vname' => 'LBL_GESTIONESFRAN',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',    
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',        
    'source' => 'non-db',
    ),
    'llamadaspendientesfran' =>
        array(
            'required' => false,
    'name' => 'llamadaspendientesfran',
    'vname' => 'LBL_LLAMADASPENDIENTESFRAN',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',    
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',        
    'source' => 'non-db',
    ),
    
    
   'num_solicitudes' =>
 array(
 'massupdate' => false,
 'name' => 'num_solicitudes',
 'type' => 'int',
 'studio' => 'false',
 'source' => 'non-db',
 'vname' => 'LBL_NUMEROSOLICITUDES',
 'importable' => 'false',
 ),
 
 'total_gestiones' =>
 array(
 'massupdate' => false,
 'name' => 'total_gestiones',
 'type' => 'int',
 'studio' => 'false',
 'source' => 'non-db',
 'vname' => 'LBL_TOTALGESTIONES',
 'importable' => 'false',
 ),
 
 'dummies' =>
 array(
 'massupdate' => false,
 'name' => 'dummies',
 'type' => 'int',
 'studio' => 'false',
 'source' => 'non-db',
 'vname' => 'LBL_DUMMIES',
 'importable' => 'false',
 ),
 
 'sol_rating_a_plus' =>
 array(
 'massupdate' => false,
 'name' => 'sol_rating_a_plus',
 'type' => 'int',
 'studio' => 'false',
 'source' => 'non-db',
 'vname' => 'LBL_SOL_RATING_A_PLUS',
 'importable' => 'false',
 ),
 
 'sol_rating_a' =>
 array(
 'massupdate' => false,
 'name' => 'sol_rating_a',
 'type' => 'int',
 'studio' => 'false',
 'source' => 'non-db',
 'vname' => 'LBL_SOL_RATING_A',
 'importable' => 'false',
 ),

 'sol_rating_b' =>
 array(
 'massupdate' => false,
 'name' => 'sol_rating_b',
 'type' => 'int',
 'studio' => 'false',
 'source' => 'non-db',
 'vname' => 'LBL_SOL_RATING_B',
 'importable' => 'false',
 ),
 
 'sol_rating_c' =>
 array(
 'massupdate' => false,
 'name' => 'sol_rating_c',
 'type' => 'int',
 'studio' => 'false',
 'source' => 'non-db',
 'vname' => 'LBL_SOL_RATING_C',
 'importable' => 'false',
 ),
 
 'prime' => 
      array (
        'required' => false,
        'name' => 'prime',
        'vname' => 'LBL_PRIME',
        'type' => 'bool',
        'massupdate' => 0,
        'no_default' => false,
        'comments' => '',
        'help' => '',
        'importable' => 'true',
        'duplicate_merge' => 'disabled',
        'duplicate_merge_dom_value' => '0',
        'audited' => false,
        'reportable' => true,
        'unified_search' => false,
        'merge_filter' => 'disabled',
        'len' => '255',
        'size' => '20',
      ),
    
    
),
	'relationships'=>array (
),
	'optimistic_locking'=>true,
		'unified_search'=>true,
	);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('Expan_Franquicia','Expan_Franquicia', array('basic','assignable','company'));