<?php

$dictionary['Expan_Franquiciado'] = array(

    'table' => 'expan_franquiciado',
    'audited' => 'true',
    'fields' => array (
        'empresa' => 
  array (
    'required' => false,
    'name' => 'empresa',
    'vname' => 'LBL_EMPRESA',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'skype' => 
  array (
    'required' => false,
    'name' => 'skype',
    'vname' => 'LBL_SKYPE',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => true,
    'merge_filter' => 'disabled',
    'len' => '60',
    'size' => '20',
  ),
  'no_newsletter' => 
  array (
    'required' => false,
    'name' => 'no_newsletter',
    'vname' => 'LBL_NEWSLETTER',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'no_correos' => 
  array (
    'required' => false,
    'name' => 'no_correos',
    'vname' => 'LBL_NO_CORREOS',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'fecha_primer_contacto' => 
  array (
    'required' => false,
    'name' => 'fecha_primer_contacto',
    'vname' => 'LBL_FECHA_PRIMER_CONTACTO',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
    'display_default' => 'now',
  ),
  'observaciones' => 
  array (
    'required' => false,
    'name' => 'observaciones',
    'vname' => 'LBL_OBSERVACIONES',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '3',
    'cols' => '60',
  ),
  'check_plurifranquiciado' => 
  array (
    'required' => false,
    'name' => 'check_plurifranquiciado',
    'vname' => 'LBL_CHECK_PLURIFRANQUICIADO',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'origen' => array(
            'name'=> 'origen',
            'vname'=> 'LBL_ORIGEN',
            'type' => 'enum',
            'len' => '50',
            'options' => 'origen_list',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'pais' => 
  array (
    'required' => false,
    'name' => 'pais',
    'vname' => 'LBL_PAIS',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'countries_dom',
    'studio' => 'visible',
  ),
  
    ),
    'relationships'=>array (
),
    'optimistic_locking'=>true,
        'unified_search'=>true,
    );
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('Expan_Franquiciado','Expan_Franquiciado', array('basic','assignable','person'));
?>