<?php
  if (!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
  /*********************************************************************************
   * SugarCRM Community Edition is a customer relationship management program developed by
   * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
   *
   * This program is free software; you can redistribute it and/or modify it under
   * the terms of the GNU Affero General Public License version 3 as published by the
   * Free Software Foundation with the addition of the following permission added
   * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
   * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
   * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
   *
   * This program is distributed in the hope that it will be useful, but WITHOUT
   * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
   * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
   * details.
   *
   * You should have received a copy of the GNU Affero General Public License along with
   * this program; if not, see http://www.gnu.org/licenses or write to the Free
   * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
   * 02110-1301 USA.
   *
   * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
   * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
   *
   * The interactive user interfaces in modified source and object code versions
   * of this program must display Appropriate Legal Notices, as required under
   * Section 5 of the GNU Affero General Public License version 3.
   *
   * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
   * these Appropriate Legal Notices must retain the display of the "Powered by
   * SugarCRM" logo. If the display of the logo is not reasonably feasible for
   * technical reasons, the Appropriate Legal Notices must display the words
   * "Powered by SugarCRM".
   ********************************************************************************/

  $dictionary['Expan_Empresa'] = array(
    'table' => 'expan_empresa',
    'audited' => true,
    'duplicate_merge' => true,
    'fields' => array(

      //----- otros ------------------------------------------------------


      'chk_alianza' =>
        array(
          'required' => false,
          'name' => 'chk_alianza',
          'vname' => 'LBL_ALIANZA',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),

      'otros_sectores' =>
        array(
          'required' => false,
          'name' => 'otros_sectores',
          'vname' => 'LBL_OTROS_SECTORES',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '10',
          'studio' => 'visible',
          'rows' => '2',
          'cols' => '60',
        ),

      'pais' =>
        array(
          'required' => false,
          'name' => 'pais',
          'vname' => 'LBL_PAIS',
          'type' => 'enum',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'options' => 'countries_dom',
          'studio' => 'visible',
          'isMultiSelect' => true,
        ),

      'razon_social' =>
        array(
          'required' => false,
          'name' => 'razon_social',
          'vname' => 'LBL_RAZON_SOCIAL',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

      // ---- DATOS CLIENTE POTENCIAL --------------------------------------------------------------------------------------------

      'rating' =>
        array(
          'required' => false,
          'name' => 'rating',
          'vname' => 'LBL_RATING',
          'type' => 'enum',
          'massupdate' => '1',
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => 4,
          'size' => '20',
          'options' => 'rating_list_calidad_propuesta',
          'studio' => 'visible',
          'dependency' => false,
        ),

      'estado_cp' =>
        array(
          'required' => false,
          'name' => 'estado_cp',
          'vname' => 'LBL_ESTADO',
          'type' => 'enum',
          'massupdate' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => 5,
          'size' => '20',
          'options' => 'estado_cp_list',
          'studio' => 'visible',
          'dependency' => false,
        ),

      'positivo_cp' =>
        array(
          'required' => false,
          'name' => 'positivo_cp',
          'vname' => 'LBL_POSITIVO_CP',
          'type' => 'enum',
          'massupdate' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => 5,
          'size' => '20',
          'options' => 'estado_tipo_positivo_cp_list',
          'studio' => 'visible',
          'dependency' => false,
        ),

      'observaciones_estado' =>
        array(
          'required' => false,
          'name' => 'observaciones_estado',
          'vname' => 'LBL_OBSERVACIONES_ESTADO',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'chk_corto_plazo' =>
        array(
          'required' => false,
          'name' => 'chk_corto_plazo',
          'vname' => 'LBL_CORTO_PLAZO',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),

      'decision' =>
        array(
          'required' => false,
          'name' => 'decision',
          'vname' => 'LBL_DECISION',
          'type' => 'enum',
          'massupdate' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => 3,
          'size' => '20',
          'options' => 'tipo_decision_list',
          'studio' => 'visible',
          'dependency' => false,
        ),

      'f_plazo' =>
        array(
          'required' => false,
          'name' => 'f_plazo',
          'vname' => 'LBL_PLAZO',
          'type' => 'date',
          'massupdate' => '1',
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'enable_range_search' => false,
        ),

      'tipo_propuesta' =>
        array(
          'required' => false,
          'name' => 'tipo_propuesta',
          'vname' => 'LBL_TIPO_PROPUESTA',
          'type' => 'enum',
          'massupdate' => '1',
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => 3,
          'size' => '20',
          'options' => 'tipo_propuesta_list',
          'studio' => 'visible',
          'dependency' => false,
        ),

      'f_envio_propuesta' =>
        array(
          'required' => false,
          'name' => 'f_envio_propuesta',
          'vname' => 'LBL_ENVIO_PROPUESTA',
          'type' => 'date',
          'massupdate' => '1',
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'enable_range_search' => false,
        ),

      'observaciones_propuesta' =>
        array(
          'required' => false,
          'name' => 'observaciones_propuesta',
          'vname' => 'LBL_OBSERVACIONES_PROPUESTA',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'consultora' =>
        array(
          'required' => false,
          'name' => 'consultora',
          'vname' => 'LBL_CONSULTORA_FRANQUICIA',
          'type' => 'multienum',
          'massupdate' => 1,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'options' => 'consultoras_franquicia_list',
          'len' => 36,
          'size' => '20',
        ),

      'consultora_habla' =>
        array(
          'required' => false,
          'name' => 'consultora_habla',
          'vname' => 'LBL_CONSULTORA_FRANQUICIA_HABLA',
          'type' => 'multienum',
          'massupdate' => 1,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'options' => 'consultoras_franquicia_list',
          'len' => 36,
          'size' => '20',
        ),

      'informacion_proyecto' =>
        array(
          'required' => false,
          'name' => 'informacion_proyecto',
          'vname' => 'LBL_INFORMACION_PROYECTO',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => 'NO SON FRANQUICIA                  SON FRANQUICIA Y TRABAJAN CON CONSULTORA

Porque quieren Franquiciar.           Porque quieren cambiar de consultora. Porque no siguen con la expansion con ellos.
Le han pedido franquicias.             Cuanto tiempo llevan con ellos.
Años de actividad.                         Cuantas franquicias han conseguido.
Nº de centros.                                Reciben informes mensuales.
Nº de empleados necesarios.         Cuando se les acaba el contrato con ellos.
Inversion Necesaria.                       Que acciones de expansion han hecho
Cual es su punto diferencial.
Competencia directa.',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'chk_alta_news' =>
        array(
          'required' => false,
          'name' => 'chk_alta_news',
          'vname' => 'LBL_ALTA_NEWS',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),

      'interes_en' =>
        array(
          'required' => false,
          'name' => 'interes_en',
          'vname' => 'LBL_INTERES_EN',
          'type' => 'enum',
          'massupdate' => 1,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'options' => 'list_interes_EN',
          'len' => 5,
          'size' => '20',
        ),

      'encaje_cliente' =>
        array(
          'required' => false,
          'name' => 'encaje_cliente',
          'vname' => 'LBL_ENCAJE_CLIENTE',
          'type' => 'enum',
          'massupdate' => 1,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'options' => 'list_encaje_cliente',
          'len' => 5,
          'size' => '20',
        ),

      'motivo_no_gusta' =>
        array(
          'required' => false,
          'name' => 'motivo_no_gusta',
          'vname' => 'LBL_MOTIVO_NO_GUSTA',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '3',
          'cols' => '40',
        ),

      'motivo_no_encaja' =>
        array(
          'required' => false,
          'name' => 'motivo_no_encaja',
          'vname' => 'LBL_MOTIVO_NO_ENCAJA',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '3',
          'cols' => '40',
        ),

      'hist_conversacion' =>
        array(
          'required' => false,
          'name' => 'hist_conversacion',
          'vname' => 'LBL_HISTORICO_CONVERSACION',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'estado_proyecto' =>
        array(
          'required' => false,
          'name' => 'estado_proyecto',
          'vname' => 'LBL_ESTADO_PROYECTO',
          'type' => 'enum',
          'massupdate' => 1,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'options' => 'list_estado_proyecto',
          'len' => 5,
          'size' => '20',
        ),

      // ---- DATOS  PROVEEDORES --------------------------------------------------------------------------------------------


      'principales_prod_serv' =>
        array(
          'required' => false,
          'name' => 'principales_prod_serv',
          'vname' => 'LBL_PRINCIPALES_PROD_SERV',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

      'ambito_actuacion' =>
        array(
          'required' => false,
          'name' => 'ambito_actuacion',
          'vname' => 'LBL_AMBITO_ACTUACION',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

      'zonas_no_opera' =>
        array(
          'required' => false,
          'name' => 'zonas_no_opera',
          'vname' => 'LBL_ZONAS_NO_OPERA',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

      'sedes' =>
        array(
          'required' => false,
          'name' => 'sedes',
          'vname' => 'LBL_SEDES',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'observaciones_proveedor' =>
        array(
          'required' => false,
          'name' => 'observaciones_proveedor',
          'vname' => 'LBL_OBSERVACIONES_PROVEEDOR',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'intranet_catalogo' =>
        array(
          'required' => false,
          'name' => 'intranet_catalogo',
          'vname' => 'LBL_INTRANET_CATALOGO',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

      'cert_calidad' =>
        array(
          'required' => false,
          'name' => 'cert_calidad',
          'vname' => 'LBL_CERT_CALIDAD',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

      'chk_proveedor_cliente' =>
        array(
          'required' => false,
          'name' => 'chk_proveedor_cliente',
          'vname' => 'LBL_PROVEEDOR_CLIENTE',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),

      'chk_proveedor_activo' =>
        array(
          'required' => false,
          'name' => 'chk_proveedor_activo',
          'vname' => 'LBL_PROVEEDOR_ACTIVO',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),

      'condiciones_generales' =>
        array(
          'required' => false,
          'name' => 'condiciones_generales',
          'vname' => 'LBL_CONDICIONES_GENERALES',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => 'Ofertas/descuentos
Pedido mínimo
Formas de pago
Condiciones de portes
Plazos de entrega
Rappel a la Central
Rappel a franquiciado
Garantía de producto
Política de devoluciones
        ',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'condiciones_especiales_en' =>
        array(
          'required' => false,
          'name' => 'condiciones_especiales_en',
          'vname' => 'LBL_CONDICIONES_ESPECIALES_EN',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => 'Ofertas/descuentos
Pedido mínimo
Formas de pago
Condiciones de portes
Plazos de entrega
Rappel a la Central
Rappel a franquiciado
Garantía de producto
Política de devoluciones
        ',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),


      // ---- DATOS ALIANZA -------------------------------------------------------------------------------------------------

      'estado_alia' =>
        array(
          'required' => false,
          'name' => 'estado_alia',
          'vname' => 'LBL_ESTADO',
          'type' => 'enum',
          'massupdate' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => 5,
          'size' => '20',
          'options' => 'estado_alia_list',
          'studio' => 'visible',
          'dependency' => false,
        ),


      'f_inicio_alianza' =>
        array(
          'required' => false,
          'name' => 'f_inicio_alianza',
          'vname' => 'LBL_FECHA_INICIO_ALIANZA',
          'type' => 'date',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'enable_range_search' => true,
        ),

      'f_restriccion_alianza' =>
        array(
          'required' => false,
          'name' => 'f_restriccion_alianza',
          'vname' => 'LBL_FECHA_RESTRICCION_ALIANZA',
          'type' => 'date',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'enable_range_search' => true,
        ),

      'condiciones_alianza' =>
        array(
          'required' => false,
          'name' => 'condiciones_alianza',
          'vname' => 'LBL_CONDICIONES_ALIANZA',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'chk_alianza_central' =>
        array(
          'required' => false,
          'name' => 'chk_alianza_central',
          'vname' => 'LBL_ALIANZA_CENTRAL',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),

      'chk_alianza_fdo' =>
        array(
          'required' => false,
          'name' => 'chk_alianza_fdo',
          'vname' => 'LBL_ALIANZA_FDO',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),

      // --- DATOS COMO COMPETIDOR  ----------------------------------------------

      'const_year' =>
        array(
          'name' => 'const_year',
          'vname' => 'LBL_CONST_YEAR',
          'type' => 'int',
          'len' => 5,
          'comment' => 'Año de constitucion',
          'importable' => 'false',
          'massupdate' => false,
          'reportable' => false,
          'audited' => true,
          'studio' => 'false',
        ),

      'num_locales_propios' =>
        array(
          'name' => 'num_locales_propios',
          'vname' => 'LBL_LOCALES_PROPIOS',
          'type' => 'varchar',
          'len' => 150,
          'importable' => 'false',
          'massupdate' => false,
          'reportable' => false,
          'audited' => true,
          'studio' => 'false',
        ),

      'num_locales_franquiciados' =>
        array(
          'name' => 'num_locales_franquiciados',
          'vname' => 'LBL_LOCALES_FRANQUICIADOS',
          'type' => 'varchar',
          'len' => 150,
          'importable' => 'false',
          'massupdate' => false,
          'reportable' => false,
          'audited' => true,
          'studio' => 'false',
        ),

      'num_locales_extran' =>
        array(
          'name' => 'num_locales_extran',
          'vname' => 'LBL_LOCALES_EXTRAN',
          'type' => 'int',
          'len' => 5,
          'importable' => 'false',
          'massupdate' => false,
          'reportable' => false,
          'audited' => true,
          'studio' => 'false',
        ),

      'poblacion_min' =>
        array(
          'name' => 'poblacion_min',
          'vname' => 'LBL_POBLACION_MIN',
          'type' => 'int',
          'len' => 7,
          'importable' => 'false',
          'massupdate' => false,
          'reportable' => false,
          'audited' => true,
          'studio' => 'false',
        ),

      'sup_local_min' =>
        array(
          'name' => 'sup_local_min',
          'vname' => 'SUP_LOCAL_MIN',
          'type' => 'int',
          'len' => 5,
          'importable' => 'false',
          'massupdate' => false,
          'reportable' => false,
          'audited' => true,
          'studio' => 'false',
        ),

      'zona_prioritaria_antece' =>
        array(
          'required' => false,
          'name' => 'zona_prioritaria_antece',
          'vname' => 'LBL_ZONA_PRIORITARIA',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'otros_requisitos' =>
        array(
          'required' => false,
          'name' => 'otros_requisitos',
          'vname' => 'LBL_OTROS_REQUISITOS',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'inversion' =>
        array(
          'required' => false,
          'name' => 'inversion',
          'vname' => 'LBL_INVERSION',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '100',
          'size' => '20',
        ),

      'canon_entrada' =>
        array(
          'required' => false,
          'name' => 'canon_entrada',
          'vname' => 'LBL_CANON_ENTRADA',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '100',
          'size' => '20',
        ),

      'royalty_explotacion' =>
        array(
          'required' => false,
          'name' => 'royalty_explotacion',
          'vname' => 'LBL_ROYALTY_EXPLOTACION',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '100',
          'size' => '20',
        ),

      'fondo_marketing' =>
        array(
          'required' => false,
          'name' => 'fondo_marketing',
          'vname' => 'LBL_FONDO_MARKETING',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '100',
          'size' => '20',
        ),

      'duracion_contrato' =>
        array(
          'required' => false,
          'name' => 'duracion_contrato',
          'vname' => 'LBL_DURACION_CONTRATO',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '100',
          'size' => '20',
        ),

      'ayuda_financiera' =>
        array(
          'required' => false,
          'name' => 'ayuda_financiera',
          'vname' => 'LBL_AYUDA_FINANCIERA',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '100',
          'size' => '20',
        ),

      'perfil_candidato' =>
        array(
          'required' => false,
          'name' => 'perfil_candidato',
          'vname' => 'LBL_PERFIL_CANDIDATO',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'elementos_diferenciales' =>
        array(
          'required' => false,
          'name' => 'elementos_diferenciales',
          'vname' => 'LBL_ELEM_DIFERENCIALES',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'ferias' =>
        array(
          'required' => false,
          'name' => 'ferias',
          'vname' => 'LBL_FERIAS',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'portales' =>
        array(
          'required' => false,
          'name' => 'portales',
          'vname' => 'LBL_PORTALES',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'mailings' =>
        array(
          'required' => false,
          'name' => 'mailings',
          'vname' => 'LBL_MAILINGS',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'publicaciones' =>
        array(
          'required' => false,
          'name' => 'publicaciones',
          'vname' => 'LBL_PUBLICACIONES',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'marketing_digital' =>
        array(
          'required' => false,
          'name' => 'marketing_digital',
          'vname' => 'LBL_MARKETING_DIGITAL',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'otras_acciones' =>
        array(
          'required' => false,
          'name' => 'otras_acciones',
          'vname' => 'LBL_OTRAS_ACCIONES',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'aperturas_propias' =>
        array(
          'required' => false,
          'name' => 'aperturas_propias',
          'vname' => 'LBL_APERTURAS_PROPIAS',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '100',
          'size' => '20',
        ),

      'aperturas_franquiciados' =>
        array(
          'required' => false,
          'name' => 'aperturas_franquiciados',
          'vname' => 'LBL_APERTURAS_FRANQUICIADOS',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '100',
          'size' => '20',
        ),

      'cierres_propios' =>
        array(
          'required' => false,
          'name' => 'cierres_propios',
          'vname' => 'LBL_CIERRES_PROPIOS',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '100',
          'size' => '20',
        ),

      'cierres_franquiciados' =>
        array(
          'required' => false,
          'name' => 'cierres_franquiciados',
          'vname' => 'LBL_CIERRES_FRANQUICIADOS',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '100',
          'size' => '20',
        ),

      'aperturas_extranjero' =>
        array(
          'required' => false,
          'name' => 'aperturas_extranjero',
          'vname' => 'LBL_APERTURAS_EXTRANJERO',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '100',
          'size' => '20',
        ),

      'cierres_extranjero' =>
        array(
          'required' => false,
          'name' => 'cierres_extranjero',
          'vname' => 'LBL_CIERRES_EXTRANJERO',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '100',
          'size' => '20',
        ),

      'personal_necesario' =>
        array(
          'required' => false,
          'name' => 'personal_necesario',
          'vname' => 'LBL_PERSONAL_NECESARIO',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '100',
          'size' => '20',
        ),

      'web' =>
        array(
          'required' => false,
          'name' => 'web',
          'vname' => 'LBL_WEB',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '100',
          'size' => '20',
        ),

      'posicionamiento_online' =>
        array(
          'required' => false,
          'name' => 'posicionamiento_online',
          'vname' => 'LBL_POSICIONAMIENTO_ONLINE',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'productos_servicios' =>
        array(
          'required' => false,
          'name' => 'productos_servicios',
          'vname' => 'LBL_PRODUCTOS_SERVICIOS',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '60',
        ),

      'noticias' =>
        array(
          'required' => false,
          'name' => 'noticias',
          'vname' => 'LBL_NOTICIAS',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '10',
          'cols' => '60',
        ),

      'chk_consultoria' =>
        array(
          'required' => false,
          'name' => 'chk_consultoria',
          'vname' => 'LBL_CHK_CONSULTORIA',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => 'Realiza trabajos de Consultoria',
          'help' => 'Realiza trabajos de Consultoria ',
          'popupHelp' => 'Realiza trabajos de Consultoria ',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),

      'd_consultoria' =>
        array(
          'required' => false,
          'name' => 'd_consultoria',
          'vname' => 'LBL_D_CONSULTORIA',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

      'chk_expansion' =>
        array(
          'required' => false,
          'name' => 'chk_expansion',
          'vname' => 'LBL_CHK_EXPANSION',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Realiza tareas de expansion',
          'popupHelp' => 'Realiza tareas de expansion',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),

      'd_expansion' =>
        array(
          'required' => false,
          'name' => 'd_expansion',
          'vname' => 'LBL_D_EXPANSION',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

      'chk_asesoramiento' =>
        array(
          'required' => false,
          'name' => 'chk_asesoramiento',
          'vname' => 'LBL_CHK_ASESORAMIENTO',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Tiene un servico de asesoramiento a emprendedores',
          'popupHelp' => 'Tiene un servico de asesoramiento a emprendedores',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),

      'd_asesoramiento' =>
        array(
          'required' => false,
          'name' => 'd_asesoramiento',
          'vname' => 'LBL_D_ASESORAMIENTO',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

      'chk_club' =>
        array(
          'required' => false,
          'name' => 'chk_club',
          'vname' => 'LBL_CHK_CLUB',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Tiene un club',
          'popupHelp' => 'Tiene un club',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),

      'd_club' =>
        array(
          'required' => false,
          'name' => 'd_club',
          'vname' => 'LBL_D_CLUB',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

      'chk_form_emp' =>
        array(
          'required' => false,
          'name' => 'chk_form_emp',
          'vname' => 'LBL_CHK_FORM_EMP',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Tiene programas de formación para empresas',
          'popupHelp' => 'Tiene programas de formación para empresas',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),

      'd_form_emp' =>
        array(
          'required' => false,
          'name' => 'd_form_emp',
          'vname' => 'LBL_D_FORM_EMP',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

        'chk_form_emprende' =>
        array(
          'required' => false,
          'name' => 'chk_form_emprende',
          'vname' => 'LBL_CHK_FORM_EMPRENDE',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Tiene programas de formación para particulares',
          'popupHelp' => 'Tiene programas de formación para particulares',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),
        'd_form_emprende' =>
        array(
          'required' => false,
          'name' => 'd_form_emprende',
          'vname' => 'LBL_D_FORM_EMPRENDE',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

      'chk_eventos_propios' =>
        array(
          'required' => false,
          'name' => 'chk_eventos_propios',
          'vname' => 'LBL_CHK_EVENTOS_PROPIOS',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Programa eventos propios',
          'popupHelp' => 'Programa eventos propios',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),
      'd_eventos_propios' =>
        array(
          'required' => false,
          'name' => 'd_eventos_propios',
          'vname' => 'LBL_D_EVENTOS_PROPIOS',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

        'chk_software_propio' =>
        array(
          'required' => false,
          'name' => 'chk_software_propio',
          'vname' => 'LBL_CHK_SOFTWARE_PROPIO',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Tienen software especifico que comercializan',
          'popupHelp' => 'Tienen software especifico que comercializan',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),

      'd_software_propio' =>
        array(
          'required' => false,
          'name' => 'd_software_propio',
          'vname' => 'LBL_D_SOFTWARE_PROPIO',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

        'chk_particulares' =>
        array(
          'required' => false,
          'name' => 'chk_particulares',
          'vname' => 'LBL_CHK_PARTICULARES',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Su servicio es solo para franquiciados',
          'popupHelp' => 'Su servicio es solo para franquiciados',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),
        'd_particulares' =>
        array(
          'required' => false,
          'name' => 'd_particulares',
          'vname' => 'LBL_D_PARTICULARES',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

      'chk_otros_PS' =>
        array(
          'required' => false,
          'name' => 'chk_otros_PS',
          'vname' => 'LBL_CHK_OTROS_PS',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Añade más productos o servicios ',
          'popupHelp' => 'Añade más productos o servicios ',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),
      'd_otros_PS' =>
        array(
          'required' => false,
          'name' => 'd_otros_PS',
          'vname' => 'LBL_D_OTROS_PS',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '10',
          'cols' => '60',
        ),

        'chk_revista' =>
        array(
          'required' => false,
          'name' => 'chk_revista',
          'vname' => 'LBL_CHK_REVISTA',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Publica una revista',
          'popupHelp' => 'Publica una revista',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),
        'd_revista' =>
        array(
          'required' => false,
          'name' => 'd_revista',
          'vname' => 'LBL_D_REVISTA',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

        'chk_portal' =>
        array(
          'required' => false,
          'name' => 'chk_portal',
          'vname' => 'LBL_CHK_PORTAL',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Tienen un portal de franquicias + ¿Qué portal?',
          'popupHelp' => 'Tienen un portal de franquicias + ¿Qué portal?',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),
      'd_portal' =>
        array(
          'required' => false,
          'name' => 'd_portal',
          'vname' => 'LBL_D_PORTAL',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

      'chk_mailing' =>
        array(
          'required' => false,
          'name' => 'chk_mailing',
          'vname' => 'LBL_CHK_MAILING',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'comercializa campañas de mailling ',
          'popupHelp' => 'comercializa campañas de mailling ',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),
      'd_mailing' =>
        array(
          'required' => false,
          'name' => 'd_mailing',
          'vname' => 'LBL_D_MAILING',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

      'chk_podcast' =>
        array(
          'required' => false,
          'name' => 'chk_podcast',
          'vname' => 'LBL_CHK_PODCAST',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Realiza un podcast',
          'popupHelp' => 'Realiza un podcast',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),
      'd_podcast' =>
        array(
          'required' => false,
          'name' => 'd_podcast',
          'vname' => 'LBL_D_PODCAST',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

      'chk_radio' =>
        array(
          'required' => false,
          'name' => 'chk_radio',
          'vname' => 'LBL_CHK_RADIO',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Se publicita o gestiona un programa de radio',
          'popupHelp' => 'Se publicita o gestiona un programa de radio',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),
      'd_radio' =>
        array(
          'required' => false,
          'name' => 'd_radio',
          'vname' => 'LBL_D_RADIO',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

      'chk_tv' =>
        array(
          'required' => false,
          'name' => 'chk_tv',
          'vname' => 'LBL_CHK_TV',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Se publicita o tiene un espacio televisivo',
          'popupHelp' => 'Se publicita o tiene un espacio televisivo',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),
      'd_tv' =>
        array(
          'required' => false,
          'name' => 'd_tv',
          'vname' => 'LBL_D_TV',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

      'chk_newsletter' =>
        array(
          'required' => false,
          'name' => 'chk_newsletter',
          'vname' => 'LBL_CHK_NEWSLETTER',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Publica newsletter',
          'popupHelp' => 'Publica newsletter',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),

      'chk_facebook' =>
        array(
          'required' => false,
          'name' => 'chk_facebook',
          'vname' => 'LBL_CHK_FACEBOOK',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Añadir enlace de esta red social',
          'popupHelp' => 'Añadir enlace de esta red social',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),
      'd_facebook' =>
        array(
          'required' => false,
          'name' => 'd_facebook',
          'vname' => 'LBL_D_FACEBOOK',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

        'chk_instagram' =>
        array(
          'required' => false,
          'name' => 'chk_instagram',
          'vname' => 'LBL_CHK_INSTAGRAM',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Añadir enlace de esta red social',
          'popupHelp' => 'Añadir enlace de esta red social',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),
        'd_instagram' =>
        array(
          'required' => false,
          'name' => 'd_instagram',
          'vname' => 'LBL_D_instagram',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

      'chk_youtube' =>
        array(
          'required' => false,
          'name' => 'chk_youtube',
          'vname' => 'LBL_CHK_YOUTUBE',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Añadir enlace de esta red social',
          'popupHelp' => 'Añadir enlace de esta red social',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),
      'd_youtube' =>
        array(
          'required' => false,
          'name' => 'd_youtube',
          'vname' => 'LBL_D_YOUTUBE',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

        'chk_linkedin' =>
        array(
          'required' => false,
          'name' => 'chk_linkedin',
          'vname' => 'LBL_CHK_LINKEDIN',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Añadir enlace de esta red social',
          'popupHelp' => 'Añadir enlace de esta red social',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),
        'd_linkedin' =>
        array(
          'required' => false,
          'name' => 'd_linkedin',
          'vname' => 'LBL_D_LINKEDIN',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

        'chk_twitter' =>
        array(
          'required' => false,
          'name' => 'chk_twitter',
          'vname' => 'LBL_CHK_TWITTER',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Añadir enlace de esta red social',
          'popupHelp' => 'Añadir enlace de esta red social',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),
        'd_twitter' =>
        array(
          'required' => false,
          'name' => 'd_twitter',
          'vname' => 'LBL_D_TWITTER',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '20',
        ),

        'chk_pinterest' =>
        array(
          'required' => false,
          'name' => 'chk_pinterest',
          'vname' => 'LBL_CHK_PINTEREST',
          'type' => 'bool',
          'massupdate' => 0,
          'default' => '0',
          'no_default' => false,
          'comments' => '',
          'help' => 'Añadir enlace de esta red social',
          'popupHelp' => 'Añadir enlace de esta red social',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
        ),
        'd_pinterest' =>
        array(
          'required' => false,
          'name' => 'd_pinterest',
          'vname' => 'LBL_D_PINTEREST',
          'type' => 'varchar',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'len' => '255',
          'size' => '60',
        ),


        'noticias_destacadas' =>
        array(
          'required' => false,
          'name' => 'noticias_destacadas',
          'vname' => 'LBL_NOTICIAS_DESTACADAS',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => 'Noticias en medios sobre la empresa',
          'popupHelp' => 'Noticias en medios sobre la empresa',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '10',
          'cols' => '60',
        ),

        'acuerdos_relevantes' =>
        array(
          'required' => false,
          'name' => 'acuerdos_relevantes',
          'vname' => 'LBL_D_ACUERDOS_RELEVANTES',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => 'Noticias de acuerdos alcanzados con otras empresas',
          'popupHelp' => 'Noticias de acuerdos alcanzados con otras empresas',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '10',
          'cols' => '60',
        ),
        'campa_sem' =>
        array(
          'required' => false,
          'name' => 'campa_sem',
          'vname' => 'LBL_CAMPA_SEM',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => 'Deteccion de campañas de sem que esten realizando',
          'popupHelp' => 'Deteccion de campañas de sem que esten realizando',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '10',
          'cols' => '60',
        ),
        'presencia_eventos' =>
        array(
          'required' => false,
          'name' => 'presencia_eventos',
          'vname' => 'LBL_PRESENCIA_EVENTOS',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => 'Noticias de presencia en eventos',
          'popupHelp' => 'Noticias de presencia en eventos',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '10',
          'cols' => '60',
        ),
        'noticias_newsletter' =>
        array(
          'required' => false,
          'name' => 'noticias_newsletter',
          'vname' => 'LBL_NOTICIAS_NEWSLETTER',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => 'Noticias en newsletter propio o de su portal',
          'popupHelp' => 'Noticias en newsletter propio o de su portal',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '10',
          'cols' => '60',
        ),
        'noticias_rrss' =>
        array(
          'required' => false,
          'name' => 'noticias_rrss',
          'vname' => 'LBL_NOTICIAS_RRSS',
          'type' => 'text',
          'massupdate' => 0,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'disabled',
          'duplicate_merge_dom_value' => '0',
          'audited' => true,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'size' => '20',
          'studio' => 'visible',
          'rows' => '10',
          'cols' => '60',
        ),
    ),

    'relationships' => array(),
    'optimistic_locking' => true,
    'unified_search' => true,
  );
  if (!class_exists('VardefManager')) {
    require_once('include/SugarObjects/VardefManager.php');
  }
  VardefManager::createVardef('Expan_Empresa', 'Expan_Empresa', array('basic', 'assignable', 'empresa'));