<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$dictionary['Expan_GestionSolicitudes'] = array(
	'table'=>'expan_gestionsolicitudes',
	'audited'=>true,
		'duplicate_merge'=>true,
		'fields'=>array (  'chk_envio_documentacion' => 
  array (
    'required' => false,
    'name' => 'chk_envio_documentacion',
    'vname' => 'Envio de la documentacion (C1)',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'popupHelp' => 'Cuestionario, dosier y multimedia',    
  ),
  'chk_resolucion_dudas' => 
  array (
    'required' => false,
    'name' => 'chk_resolucion_dudas',
    'vname' => 'Resolucion de dudas (Llaman ellos)',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',    
  ),
  'f_resolucion_dudas' => 
  array (
    'required' => false,
    'name' => 'f_resolucion_dudas',
    'vname' => 'Fecha de Resolucion de dudas',
    'type' => 'date',
    'massupdate' => 0,    
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'enable_range_search' => false,
  ),
  
  'chk_sol_amp_info' => 
  array (
    'required' => false,
    'name' => 'chk_sol_amp_info',
    'vname' => 'Solicitud ampliacion información (Llamamos nosotros)',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'f_sol_amp_info' => 
  array (
    'required' => false,
    'name' => 'f_sol_amp_info',
    'vname' => 'Fecha Solicitud ampliacion información ',
    'type' => 'date',
    'massupdate' => 0,    
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'enable_range_search' => false,
  ),
  
  'chk_recepcio_cuestionario' => 
  array (
    'required' => false,
    'name' => 'chk_recepcio_cuestionario',
    'vname' => 'LBL_RECEPCION_CUESTIONARIO',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'popupHelp' => 'Se activa cuando el solicitante rellena el cuestionario. Es de activación automática, no es necesario que el usuario la active',
  ),
  'f_recepcion_cuestionario' => 
  array (
    'required' => false,
    'name' => 'f_recepcion_cuestionario',
    'vname' => 'Fecha de recepción del cuestionario',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'enable_range_search' => false,
  ),
  'chk_informacion_adicional' => 
  array (
    'required' => false,
    'name' => 'chk_informacion_adicional',
    'vname' => 'Envio información adicional (C2)',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'popupHelp' => 'Plan financiero',
  ),
  'f_informacion_adicional' => 
  array (
    'required' => false,
    'name' => 'f_informacion_adicional',
    'vname' => 'Fecha envio información adicional',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'enable_range_search' => false,
  ), 
  'chk_responde_C1' => 
  array (
    'required' => false,
    'name' => 'chk_responde_C1',
    'vname' => 'LBL_RESPONDE_C1',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'popupHelp' => 'Se activa si el usuario responde al C1. Es de activación automática no es necesario que el usuario la active',
  ),
  'f_responde_C1' => 
  array (
    'required' => false,
    'name' => 'f_responde_C1',
    'vname' => 'Fecha resolucion C1',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'enable_range_search' => false,
  ),
  
  'chk_entrevista' => 
  array (
    'required' => false,
    'name' => 'chk_entrevista',
    'vname' => 'Entrevista',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'popupHelp' => 'Presencial, virtual o entrevista preconcertada en feria',
  ),
  'f_entrevista' => 
  array (
    'required' => false,
    'name' => 'f_entrevista',
    'vname' => 'Fecha Entrevista',
    'type' => 'date',
    'massupdate' => '1',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'enable_range_search' => false,
  ),
  
  'chk_propuesta_zona' => 
  array (
    'required' => false,
    'name' => 'chk_propuesta_zona',
    'vname' => 'LBL_ENVIO_PROP_ZONA',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'f_propuesta_zona' => 
  array (
    'required' => false,
    'name' => 'f_propuesta_zona',
    'vname' => 'LBL_F_ENVIO_PROP_ZONA',
    'type' => 'date',
    'massupdate' => 0,    
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'enable_range_search' => false,
  ),
  
    'chk_visitado_fran' => 
  array (
    'required' => false,
    'name' => 'chk_visitado_fran',
    'vname' => 'Visitado franquiciado / unidad propia',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'f_visitado_fran' => 
  array (
    'required' => false,
    'name' => 'f_visitado_fran',
    'vname' => 'Fecha Visitado franquiciado',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'enable_range_search' => false,
  ),
  'chk_envio_precontrato' => 
  array (
    'required' => false,
    'name' => 'chk_envio_precontrato',
    'vname' => 'Envio precontrato',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'f_envio_precontrato' => 
  array (
    'required' => false,
    'name' => 'f_envio_precontrato',
    'vname' => 'Fecha envio precontrato',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'enable_range_search' => false,
  ),
  'chk_visita_local' => 
  array (
    'required' => false,
    'name' => 'chk_visita_local',
    'vname' => 'LBL_INFORMACION_LOCAL',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'f_visita_local' => 
  array (
    'required' => false,
    'name' => 'f_visita_local',
    'vname' => 'Fecha visita al local',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'enable_range_search' => false,
  ),
  'chk_envio_contrato' => 
  array (
    'required' => false,
    'name' => 'chk_envio_contrato',
    'vname' => 'Envío de contrato',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'f_envio_contrato' => 
  array (
    'required' => false,
    'name' => 'f_envio_contrato',
    'vname' => 'Fecha envío de contrato',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'enable_range_search' => false,
  ),
  
  'chk_visita_central' => 
  array (
    'required' => false,
    'name' => 'chk_visita_central',
    'vname' => 'Visita a la Central',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'f_visita_central' => 
  array (
    'required' => false,
    'name' => 'f_visita_central',
    'vname' => 'Fecha visita a la Central',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'enable_range_search' => false,
  ),
  
    'chk_posible_colabora' => 
  array (
    'required' => false,
    'name' => 'chk_posible_colabora',
    'vname' => 'Posible Colaboracion',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'popupHelp' => 'Interesado en comprar servicios o productos sin ser franquiciado. Todavía no es positivo.',
  ),
  'f_posible_colabora' => 
  array (
    'required' => false,
    'name' => 'f_posible_colabora',
    'vname' => 'Fecha Posible Colaboracion',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'enable_range_search' => false,
  ),
  
  
  'candidatura_caliente' => 
  array (
    'required' => false,
    'name' => 'candidatura_caliente',
    'vname' => 'Candidatura caliente',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
  'candidatura_avanzada' => 
  array (
    'required' => false,
    'name' => 'candidatura_avanzada',
    'vname' => 'LBL_CANDIDATURA_AVANZADA',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
  'estado_sol' => 
  array (
    'required' => false,
    'name' => 'estado_sol',
    'vname' => 'Estado',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'estado_sol_list',
    'studio' => 'visible',
    'dependency' => false,
    'default' => '1',
  ),
  
  'envio_documentacion' => 
  array (
    'required' => false,
    'name' => 'envio_documentacion',
    'vname' => 'Fecha de envio de Documentación',
    'type' => 'date',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  
    'franquicia' => 
  array (
    'required' => false,
    'name' => 'franquicia',
    'vname' => 'LBL_FRANQUICIA',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'link' => true,
    'options' => 'franquicia_list_todas',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
    'observaciones_informe' => 
  array (
    'required' => false,
    'name' => 'observaciones_informe',
    'vname' => 'LBL_OBSERVACIONES_INFORME',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '20',
    'cols' => '80',
    'popupHelp' => 'Añadir <b>SOLO</b> informacion que aporte valor al franquiciador',
  ),
  
    'chk_envio_auto' => 
  array (
    'required' => false,
    'name' => 'chk_envio_auto',
    'vname' => 'Envios automatizados',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
  'cuando_empezar' => 
  array (
    'required' => false,
    'name' => 'cuando_empezar',
    'vname' => 'LBL_CUANDO_EMPEZAR',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  
  
/*  'cuando_empezar' => 
  array (
    'required' => false,
    'name' => 'cuando_empezar',
    'vname' => 'LBL_CUANDO_EMPEZAR',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'cuando_empezar_list',
    'studio' => 'visible',
    'dependency' => false,
  ),*/
  
  'prioridad' =>
  array (
    'name' => 'prioridad',
    'vname' => 'LBL_PRIORIDAD',
    'type' => 'int',
    'len' => '3',
    'default' => 0,
    'audited' => true,
    'reportable' => false,
    'unified_search' => false,
    'comment' => 'Prioridad de la Gestion',
  ),
  
  'oportunidad_inmediata' => 
  array (
    'required' => false,
    'name' => 'oportunidad_inmediata',
    'vname' => 'LBL_OPORTUNIDAD_INMEDIATA',
    'type' => 'bool',
    'massupdate' => 1,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'size' => '10',
  ),
  
  'observaciones_descarte' => 
  array (
    'required' => false,
    'name' => 'observaciones_descarte',
    'vname' => 'LBL_OBSERVACIONES_DESCARTE',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '10',
    'cols' => '40',
  ),
  
  'motivo_descarte' => 
  array (
    'required' => false,
    'name' => 'motivo_descarte',
    'vname' => 'LBL_MOTIVO_DESCARTE',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'link' => true,
    'options' => 'motivo_descarte_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'motivo_parada' => 
  array (
    'required' => false,
    'name' => 'motivo_parada',
    'vname' => 'LBL_MOTIVO_PARADA',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'link' => true,
    'options' => 'motivo_parada_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'motivo_positivo' => 
  array (
    'required' => false,
    'name' => 'motivo_positivo',
    'vname' => 'LBL_MOTIVO_POSITIVO',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'link' => true,
    'options' => 'motivo_positivo_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'tipo_origen' => 
  array (
    'required' => true,
    'name' => 'tipo_origen',
    'vname' => 'LBL_TIPO_ORIGEN',
    'type' => 'enum',
    'massupdate' => 1,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'tipo_origen_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'portal' => 
  array (
    'required' => false,
    'name' => 'portal',
    'vname' => 'LBL_PORTAL',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'portal_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'subor_medios' => 
  array (
    'required' => false,
    'name' => 'subor_medios',
    'vname' => 'LBL_SUBOR_MEDIOS',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'subor_medios_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'subor_central' => 
  array (
    'required' => false,
    'name' => 'subor_central',
    'vname' => 'LBL_SUBOR_CENTRAL',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'subor_central_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'subor_expande' => 
  array (
    'required' => false,
    'name' => 'subor_expande',
    'vname' => 'LBL_SUBOR_EXPANDE',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'subor_expande_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'subor_mailing' => 
  array (
    'required' => false,
    'name' => 'subor_mailing',
    'vname' => 'LBL_SUBOR_MAILING',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'subor_mailing_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'expan_evento_id_c' => 
  array (
    'required' => false,
    'name' => 'expan_evento_id_c',
    'vname' => 'LBL_EVENTO',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'eventos_list',
    'studio' => 'visible',
    'dependency' => false,
  ), 
  'evento_bk' => 
  array (
    'required' => false,
    'name' => 'evento_bk',
    'vname' => 'LBL_EVENTO',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'eventos_list',
    'studio' => 'visible',
    'dependency' => false,
  ), 
  
  
  'lnk_cuestionario' => 
  array (
    'required' => false,
    'name' => 'lnk_cuestionario',
    'vname' => 'LBL_CUESTIONARIO',
    'type' => 'text',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 300,
    'size' => '20',
    'link' => true,
    'studio' => 'visible',
    'dependency' => false,
    'readonly' => true,
    'popupHelp' => 'No editar el cuestionario aquellos datos que ya se recojen en el CRM',
  ),
  
  'tiponegocio1' => 
  array (
    'required' => false,
    'name' => 'tiponegocio1',
    'vname' => 'LBL_TIPONEG1',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),

'chkvalNeg11' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg11',
    'vname' => 'LBL_CHKVALNEG11',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),

  'chkvalNeg12' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg12',
    'vname' => 'LBL_CHKVALNEG12',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),

  'chkvalNeg13' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg13',
    'vname' => 'LBL_CHKVALNEG13',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),

  'chkvalNeg14' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg14',
    'vname' => 'LBL_CHKVALNEG14',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),

  'chkvalNeg15' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg15',
    'vname' => 'LBL_CHKVALNEG15',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),
 
  'tiponegocio2' => 
  array (
    'required' => false,
    'name' => 'tiponegocio2',
    'vname' => 'LBL_TIPONEG2',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),


  'chkvalNeg21' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg21',
    'vname' => 'LBL_CHKVALNEG21',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),

  'chkvalNeg22' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg22',
    'vname' => 'LBL_CHKVALNEG22',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),

  'chkvalNeg23' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg23',
    'vname' => 'LBL_CHKVALNEG23',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),

  'chkvalNeg24' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg24',
    'vname' => 'LBL_CHKVALNEG24',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),

  'chkvalNeg25' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg25',
    'vname' => 'LBL_CHKVALNEG25',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),


  'tiponegocio3' => 
  array (
    'required' => false,
    'name' => 'tiponegocio3',
    'vname' => 'LBL_TIPONEG3',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),


  'chkvalNeg31' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg31',
    'vname' => 'LBL_CHKVALNEG31',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),

  'chkvalNeg32' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg32',
    'vname' => 'LBL_CHKVALNEG32',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),

  'chkvalNeg33' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg33',
    'vname' => 'LBL_CHKVALNEG33',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),

  'chkvalNeg34' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg34',
    'vname' => 'LBL_CHKVALNEG34',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),

  'chkvalNeg35' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg35',
    'vname' => 'LBL_CHKVALNEG35',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),


  
  'tiponegocio4' => 
  array (
    'required' => false,
    'name' => 'tiponegocio4',
    'vname' => 'LBL_TIPONEG4',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),

  'chkvalNeg41' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg41',
    'vname' => 'LBL_CHKVALNEG41',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),

  'chkvalNeg42' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg42',
    'vname' => 'LBL_CHKVALNEG42',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),

  'chkvalNeg43' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg43',
    'vname' => 'LBL_CHKVALNEG43',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),

  'chkvalNeg44' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg44',
    'vname' => 'LBL_CHKVALNEG44',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),

  'chkvalNeg45' => 
  array (
    'required' => false,
    'name' => 'chkvalNeg45',
    'vname' => 'LBL_CHKVALNEG45',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '1',
    'size' => '20',
  ),
  
  'inversion'=>
  array (
    'required' => false,
    'name' => 'inversion',
    'vname' => 'LBL_INVERSION',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'capital_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
    'recursos_propios'=>
  array (
    'required' => false,
    'name' => 'recursos_propios',
    'vname' => 'LBL_RECURSOS_PROPIOS',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'recursos_propios_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'papel'=>
  array (
    'required' => false,
    'name' => 'papel',
    'vname' => 'LBL_PAPEL',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'perfil_fran_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'dummie' => 
  array (
    'required' => false,
    'name' => 'dummie',
    'vname' => 'dummie',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
  'provincia_apertura_1' => 
  array (
    'required' => false,
    'name' => 'provincia_apertura_1',
    'vname' => 'LBL_PROVINCIA_APERTURA_1',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'provincias_list',
    'studio' => 'visible',
    'dependency' => false,
    'source' => 'non-db',
  ),  
    
  'rating' => 
  array (
    'required' => false,
    'name' => 'rating',
    'vname' => 'LBL_RATING',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'rating_list',
    'studio' => 'visible',
    'dependency' => false,
    'source' => 'non-db',
  ),
  
  'telefono' => 
  array (
    'required' => false,
    'name' => 'telefono',
    'vname' => 'LBL_TELEFONO',
    'type' => 'phone',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'studio' => 'visible',
    'dependency' => false,
    'source' => 'non-db',
  ),
  
  'perfil_ideoneo' => 
  array (
    'required' => false,
    'name' => 'perfil_ideoneo',
    'vname' => 'LBL_PERFIL_IDONEO',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'yes_no_list',
    'studio' => 'visible',
    'dependency' => false,
    'default' => '',
  ),
  
  'subestado'=>
  array(
      'name' => 'subestado',
      'vname' => 'LBL_SUBESTADO',
      'type' => 'varchar',
      'len' => '255',
      'default'=>'',
      'source' => 'non-db',
  ),
  
  'suborigen'=>
  array(
      'name' => 'suborigen',
      'vname' => 'LBL_SUBORIGEN',
      'type' => 'varchar',
      'len' => '255',
      'default'=>'',
      'source' => 'non-db',
  ),
      
  'Accesos' =>
   array(
    'name' => 'Accesos',
    'type' => 'SelectField',
    'source' => 'non-db',
    'vname' => 'Accesos',
    ),
  
  'chk_envio_precontrato_personal' => 
  array (
    'required' => false,
    'name' => 'chk_envio_precontrato_personal',
    'vname' => 'LBL_ENVIO_PRECONTRATO_PERSONAL',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'f_envio_precontrato_personal' => 
  array (
    'required' => false,
    'name' => 'f_envio_precontrato_personal',
    'vname' => 'LBL_FECHA_ENVIO_PRECONTRATO_PERSONAL',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'enable_range_search' => false,
  ),
  
  'chk_envio_contrato_personal' => 
  array (
    'required' => false,
    'name' => 'chk_envio_contrato_personal',
    'vname' => 'LBL_ENVIO_CONTRATO_PERSONAL',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'f_envio_contrato_personal' => 
  array (
    'required' => false,
    'name' => 'f_envio_contrato_personal',
    'vname' => 'LBL_FECHA_ENVIO_CONTRATO_PERSONAL',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'enable_range_search' => false,
  ),
  'chk_envio_plan_financiero_personal' => 
  array (
    'required' => false,
    'name' => 'chk_envio_plan_financiero_personal',
    'vname' => 'LBL_ENVIO_PLAN_FINANCIERO_PERSONAL',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'f_envio_plan_financiero_personal' => 
  array (
    'required' => false,
    'name' => 'f_envio_plan_financiero_personal',
    'vname' => 'LBL_FECHA_PLAN_FINANCIERO_PERSONAL',
    'type' => 'date',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'enable_range_search' => false,
  ),
  'rating' => 
  array (
    'required' => false,
    'name' => 'rating',
    'vname' => 'LBL_RATING',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'rating_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'preguntas_mn_t' => 
  array (
    'required' => false,
    'name' => 'preguntas_mn_t',
    'vname' => 'LBL_PREGUNTAS_MN_T',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '20',
    'cols' => '80',
    'popupHelp' => 'Preguntas realizadas por el solicitante sobre el modelo de negocio o técnicas de la actividad en las conversaciones mantenidas',
  ),
  
  'objeciones_mn' => 
  array (
    'required' => false,
    'name' => 'objeciones_mn',
    'vname' => 'LBL_OBJECIONES_MN',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '20',
    'cols' => '80',
    'popupHelp' => 'Objeciones sobre el modelo de negocio por el solicitante en las conversaciones mantenidas',
  ),
  
  'solicitudes_candidato' => 
  array (
    'required' => false,
    'name' => 'solicitudes_candidato',
    'vname' => 'LBL_SOLICITUDES_CANDIDATO',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '20',
    'cols' => '80',
    'popupHelp' => 'Solicitudes realizadas por el solicitante en las conversaciones mantenidas',
  ),
  
  'informacion_competencia' => 
  array (
    'required' => false,
    'name' => 'informacion_competencia',
    'vname' => 'LBL_INFORMACION_COMPETENCIA',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '20',
    'cols' => '80',
    'popupHelp' => 'Informacion de la compatencia que nos proporciona el solicitante en las conversaciones mantenidas',
  ),
  
  'mejoras' => 
  array (
    'required' => false,
    'name' => 'mejoras',
    'vname' => 'LBL_MEJORAS',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '20',
    'cols' => '80',
    'popupHelp' => 'Mejoras indicadas por el solicitante en las conversaciones mantenidas',
  ),
  
  'concesiones' => 
  array (
    'required' => false,
    'name' => 'concesiones',
    'vname' => 'LBL_CONCESIONES',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '20',
    'cols' => '80',    
  ),
  
  'preg_en_central' => 
  array (
    'required' => false,
    'name' => 'preg_en_central',
    'vname' => 'LBL_PREG_EN_CENTRAL',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '20',
    'cols' => '80',    
  ),
  
  'notas_argumentario' => 
  array (
    'required' => false,
    'name' => 'notas_argumentario',
    'vname' => 'LBL_NOTAS_ARGUMENTARIO',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '20',
    'cols' => '80',  
    'popupHelp' => 'Información recogida del franquiciador',
  ),
   
),
	'relationships'=>array (
),
	'optimistic_locking'=>true,
		'unified_search'=>true,
	);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('Expan_GestionSolicitudes','Expan_GestionSolicitudes', array('basic','assignable'));