<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$relationships = array (
  'expan_gestionsolicitudes_modified_user' => 
  array (
    'id' => 'dc4df17f-615a-2152-de91-583dca3e76df',
    'relationship_name' => 'expan_gestionsolicitudes_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Expan_GestionSolicitudes',
    'rhs_table' => 'expan_gestionsolicitudes',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'expan_gestionsolicitudes_created_by' => 
  array (
    'id' => 'de1ba004-728e-9a4a-2a1f-583dcac24e9a',
    'relationship_name' => 'expan_gestionsolicitudes_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Expan_GestionSolicitudes',
    'rhs_table' => 'expan_gestionsolicitudes',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'expan_gestionsolicitudes_assigned_user' => 
  array (
    'id' => 'df32b0a5-17a6-0a6f-5426-583dca9fe2d7',
    'relationship_name' => 'expan_gestionsolicitudes_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Expan_GestionSolicitudes',
    'rhs_table' => 'expan_gestionsolicitudes',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'expan_gestionsolicitudes_activities_1_calls' => 
  array (
    'id' => 'e3fde309-09e5-cfd8-f761-583dca0432bd',
    'relationship_name' => 'expan_gestionsolicitudes_activities_1_calls',
    'lhs_module' => 'Expan_GestionSolicitudes',
    'lhs_table' => 'expan_gestionsolicitudes',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Expan_GestionSolicitudes',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'expan_gestionsolicitudes_activities_1_meetings' => 
  array (
    'id' => 'e64190e1-b71f-e45d-cf0f-583dcab54600',
    'relationship_name' => 'expan_gestionsolicitudes_activities_1_meetings',
    'lhs_module' => 'Expan_GestionSolicitudes',
    'lhs_table' => 'expan_gestionsolicitudes',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Expan_GestionSolicitudes',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'expan_gestionsolicitudes_activities_1_notes' => 
  array (
    'id' => 'e751b70c-cc48-c4fe-5dae-583dcaa0fab9',
    'relationship_name' => 'expan_gestionsolicitudes_activities_1_notes',
    'lhs_module' => 'Expan_GestionSolicitudes',
    'lhs_table' => 'expan_gestionsolicitudes',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Expan_GestionSolicitudes',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'expan_gestionsolicitudes_activities_1_tasks' => 
  array (
    'id' => 'e888168d-b247-b4d7-4be4-583dca4dce35',
    'relationship_name' => 'expan_gestionsolicitudes_activities_1_tasks',
    'lhs_module' => 'Expan_GestionSolicitudes',
    'lhs_table' => 'expan_gestionsolicitudes',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Expan_GestionSolicitudes',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'expan_gestionsolicitudes_calls_1' => 
  array (
    'id' => 'e9fdd718-64f1-25e1-a663-583dca600d99',
    'relationship_name' => 'expan_gestionsolicitudes_calls_1',
    'lhs_module' => 'Expan_GestionSolicitudes',
    'lhs_table' => 'expan_gestionsolicitudes',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'id',
    'join_table' => 'expan_gestionsolicitudes_calls_1_c',
    'join_key_lhs' => 'expan_gestionsolicitudes_calls_1expan_gestionsolicitudes_ida',
    'join_key_rhs' => 'expan_gestionsolicitudes_calls_1calls_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'expan_gestionsolicitudes_meetings_1' => 
  array (
    'id' => 'eb3dad58-a2e9-51ba-b2f0-583dcadc172f',
    'relationship_name' => 'expan_gestionsolicitudes_meetings_1',
    'lhs_module' => 'Expan_GestionSolicitudes',
    'lhs_table' => 'expan_gestionsolicitudes',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'id',
    'join_table' => 'expan_gestionsolicitudes_meetings_1_c',
    'join_key_lhs' => 'expan_gestionsolicitudes_meetings_1expan_gestionsolicitudes_ida',
    'join_key_rhs' => 'expan_gestionsolicitudes_meetings_1meetings_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'expan_gestionsolicitudes_tasks_1' => 
  array (
    'id' => 'ec75f5bc-c3c0-1e35-191b-583dcaaab19d',
    'relationship_name' => 'expan_gestionsolicitudes_tasks_1',
    'lhs_module' => 'Expan_GestionSolicitudes',
    'lhs_table' => 'expan_gestionsolicitudes',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'id',
    'join_table' => 'expan_gestionsolicitudes_tasks_1_c',
    'join_key_lhs' => 'expan_gestionsolicitudes_tasks_1expan_gestionsolicitudes_ida',
    'join_key_rhs' => 'expan_gestionsolicitudes_tasks_1tasks_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'expan_solicitud_expan_gestionsolicitudes_1' => 
  array (
    'id' => 'ed97139c-8599-bff4-5ff4-583dcafc2317',
    'relationship_name' => 'expan_solicitud_expan_gestionsolicitudes_1',
    'lhs_module' => 'Expan_Solicitud',
    'lhs_table' => 'expan_solicitud',
    'lhs_key' => 'id',
    'rhs_module' => 'Expan_GestionSolicitudes',
    'rhs_table' => 'expan_gestionsolicitudes',
    'rhs_key' => 'id',
    'join_table' => 'expan_solicitud_expan_gestionsolicitudes_1_c',
    'join_key_lhs' => 'expan_solicitud_expan_gestionsolicitudes_1expan_solicitud_ida',
    'join_key_rhs' => 'expan_soli5dcccitudes_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'expan_gestionsolicitudes_expan_incidenciacorreo_1' => 
  array (
    'rhs_label' => 'IncidenciaCorreo',
    'lhs_label' => 'GestionSolicitudes',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Expan_GestionSolicitudes',
    'rhs_module' => 'Expan_IncidenciaCorreo',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'expan_gestionsolicitudes_expan_incidenciacorreo_1',
  ),
);