<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$dictionary['Expan_Solicitud'] = array(
	'table'=>'expan_solicitud',
	'audited'=>true,
		'duplicate_merge'=>true,
		'fields'=>array (
  'perfil_franquicia' => 
  array (
    'required' => false,
    'name' => 'perfil_franquicia',
    'vname' => 'LBL_PERFIL_FRANQUICIA',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'auto',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'perfil_fran_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'situacion_profesional' => 
  array (
    'required' => false,
    'name' => 'situacion_profesional',
    'vname' => 'LBL_SITUACION_PROFESIONAL',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'situacion_profesional_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'perfil_profesional' => 
  array (
    'required' => false,
    'name' => 'perfil_profesional',
    'vname' => 'LBL_PERFIL_PROFESIONAL',
	'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '64',
	
  ),
  'negocio_antes' => 
  array (
    'required' => false,
    'name' => 'negocio_antes',
    'vname' => 'LBL_NEGOCIO_ANTES',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'negocio' => 
  array (
    'required' => false,
    'name' => 'negocio',
    'vname' => 'LBL_NEGOCIO',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
  
  'cuando_empezar' => 
  array (
    'required' => false,
    'name' => 'cuando_empezar',
    'vname' => 'LBL_CUANDO_EMPEZAR',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  
 /* 'cuando_empezar' => 
  array (
    'required' => false,
    'name' => 'cuando_empezar',
    'vname' => 'LBL_CUANDO_EMPEZAR',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'cuando_empezar_list',
    'studio' => 'visible',
    'dependency' => false,
  ),*/
  
  
  
  'observaciones_solicitud' => 
  array (
    'required' => false,
    'name' => 'observaciones_solicitud',
    'vname' => 'LBL_OBSERVACIONES_SOLICITUD',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '60',
    'popupHelp'=>'Los datos contenidos en estas observaciones no llegan a la central',
  ),
  'capital' => 
  array (
    'required' => false,
    'name' => 'capital',
    'vname' => 'LBL_CAPITAL',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'capital_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'capital_observaciones' => 
  array (
    'required' => false,
    'name' => 'capital_observaciones',
    'vname' => 'LBL_CAPITAL_OBSERVACIONES',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'sectores_de_interes' => 
  array (
    'required' => false,
    'name' => 'sectores_de_interes',
    'vname' => 'LBL_SECTORES_DE_INTERES',
    'type' => 'multienum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'lst_sectores',
    'studio' => 'visible',
    'isMultiSelect' => true,
    'default' => '^^',
  ),
  'franquicia_principal' => 
  array (
    'required' => true,
    'name' => 'franquicia_principal',
    'vname' => 'LBL_FRANQUICIA_PRINCIPAL',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'franquicia_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'franquicias_secundarias' => 
  array (
    'required' => false,
    'name' => 'franquicias_secundarias',
    'vname' => 'LBL_FRANQUICIAS_SECUNDARIAS',
    'type' => 'multienum',
    'massupdate' => 0,
    'no_default' => true,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'franquicia_list',
    'studio' => 'visible',
    'isMultiSelect' => true,
  ),
  'otras_franquicias' => 
  array (
    'required' => false,
    'name' => 'otras_franquicias',
    'vname' => 'LBL_OTRAS_FRANQUICIAS',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    
  ),
  'dispone_local' => 
  array (
    'required' => false,
    'name' => 'dispone_local',
    'vname' => 'LBL_DISPONE_LOCAL',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'options' => 'lst_tipo_dispone_local',    
    'len' => '255',
    'size' => '20',
  ),
  
  'direccion_local_city' => 
  array (
    'required' => false,
    'name' => 'direccion_local_city',
    'vname' => 'LBL_DIRECCION_LOCAL_CITY',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
  ),
  'direccion_local_state' => 
  array (
    'required' => false,
    'name' => 'direccion_local_state',
    'vname' => 'LBL_DIRECCION_LOCAL_STATE',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
  ),
  'direccion_local_postalcode' => 
  array (
    'required' => false,
    'name' => 'direccion_local_postalcode',
    'vname' => 'LBL_DIRECCION_LOCAL_POSTALCODE',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 20,
    'size' => '20',
  ),
  'direccion_local_country' => 
  array (
    'required' => false,
    'name' => 'direccion_local_country',
    'vname' => 'LBL_DIRECCION_LOCAL_COUNTRY',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
  ),
  'direccion_local' => 
  array (
    'required' => false,
    'name' => 'direccion_local',
    'vname' => 'LBL_DIRECCION_LOCAL',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'superficie_local' => 
  array (
    'required' => false,
    'name' => 'superficie_local',
    'vname' => 'LBL_SUPERFICIE_LOCAL',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '20',
    'size' => '5',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => 0,
    'max' => false,
    'validation' => 
    array (
      'type' => 'range',
      'min' => 0,
      'max' => false,
    ),
  ),
  
  'ubicacion_local1' => 
  array (
    'required' => false,
    'name' => 'ubicacion_local1',
    'vname' => 'LBL_UBICACION_LOCAL1',
    'type' => 'enum',
    'massupdate' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'lst_ubicacion_local',
    'studio' => 'visible',
    'dependency' => false,
  ),
 
  'ubicacion_local2' => 
  array (
    'required' => false,
    'name' => 'ubicacion_local2',
    'vname' => 'LBL_UBICACION_LOCAL2',
    'type' => 'enum',
    'massupdate' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'lst_ubicacion_local',
    'studio' => 'visible',
    'dependency' => false,
  ),
 
   'ubicacion_local3' => 
  array (
    'required' => false,
    'name' => 'ubicacion_local3',
    'vname' => 'LBL_UBICACION_LOCAL3',
    'type' => 'enum',
    'massupdate' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'lst_ubicacion_local',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'direccion_local2' => 
  array (
    'required' => false,
    'name' => 'direccion_local2',
    'vname' => 'LBL_DIRECCION_LOCAL2',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'superficie_local2' => 
  array (
    'required' => false,
    'name' => 'superficie_local2',
    'vname' => 'LBL_SUPERFICIE_LOCAL2',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '20',
    'size' => '5',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => 0,
    'max' => false,
    'validation' => 
    array (
      'type' => 'range',
      'min' => 0,
      'max' => false,
    ),
  ),
     'direccion_local3' => 
  array (
    'required' => false,
    'name' => 'direccion_local3',
    'vname' => 'LBL_DIRECCION_LOCAL3',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'superficie_local3' => 
  array (
    'required' => false,
    'name' => 'superficie_local3',
    'vname' => 'LBL_SUPERFICIE_LOCAL3',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '20',
    'size' => '5',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => 0,
    'max' => false,
    'validation' => 
    array (
      'type' => 'range',
      'min' => 0,
      'max' => false,
    ),
  ),
  
  'descripcion_local' => 
  array (
    'required' => false,
    'name' => 'descripcion_local',
    'vname' => 'LBL_DESCRIPCION_LOCAL',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'rows' => '4',
    'cols' => '60',
  ),
  
  'descripcion_local2' => 
  array (
    'required' => false,
    'name' => 'descripcion_local2',
    'vname' => 'LBL_DESCRIPCION_LOCAL',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'rows' => '4',
    'cols' => '60',
  ),
  
  'descripcion_local3' => 
  array (
    'required' => false,
    'name' => 'descripcion_local3',
    'vname' => 'LBL_DESCRIPCION_LOCAL',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'rows' => '4',
    'cols' => '60',
  ),
  
   'renta_estimada_1' => 
  array (
    'required' => false,
    'name' => 'renta_estimada_1',
    'vname' => 'LBL_RENTA_ESTIMADA',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
  ),
  
  'renta_estimada_2' => 
  array (
    'required' => false,
    'name' => 'renta_estimada_2',
    'vname' => 'LBL_RENTA_ESTIMADA',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
  ),
  
  'renta_estimada_3' => 
  array (
    'required' => false,
    'name' => 'renta_estimada_3',
    'vname' => 'LBL_RENTA_ESTIMADA',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
  ),
  
  'estado_sol' => 
  array (
    'required' => false,
    'name' => 'estado_sol',
    'vname' => 'LBL_ESTADO_SOL',
    'type' => 'enum',
    'massupdate' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'estado_sol_list',
    'studio' => 'visible',
    'dependency' => false,
    'default' => '1',
  ),
  'motivo' => 
  array (
    'required' => false,
    'name' => 'motivo',
    'vname' => 'LBL_MOTIVO',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'candidatura_caliente' => 
  array (
    'required' => false,
    'name' => 'candidatura_caliente',
    'vname' => 'LBL_CANDIDATURA_CALIENTE',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
    'candidatura_avanzada' => 
  array (
    'required' => false,
    'name' => 'candidatura_avanzada',
    'vname' => 'LBL_CANDIDATURA_AVANZADA',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'zona' => 
  array (
    'required' => false,
    'name' => 'zona',
    'vname' => 'LBL_ZONA',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => '10',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'zonas_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'perfil_plurifranquiciado' => 
  array (
    'required' => false,
    'name' => 'perfil_plurifranquiciado',
    'vname' => 'LBL_PERFIL_PLURIFRANQUICIADO',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'perfil_plurifranquiciado_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'rating' => 
  array (
    'required' => false,
    'name' => 'rating',
    'vname' => 'LBL_RATING',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'rating_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'observaciones_candidato' => 
  array (
    'required' => false,
    'name' => 'observaciones_candidato',
    'vname' => 'LBL_OBSERVACIONES_CANDIDATO',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '60',
  ),
  
  'pais_residencia' => 
    array (
      'required' => false,
      'name' => 'pais_residencia',
      'vname' => 'LBL_PAIS_RESIDENCIA',
      'type' => 'enum',
      'massupdate' => 0,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'options' => 'countries_dom',
      'studio' => 'visible',
      'isMultiSelect' => true,
    ),
  
  'provincia_apertura_1' => 
  array (
    'required' => false,
    'name' => 'provincia_apertura_1',
    'vname' => 'LBL_PROVINCIA_APERTURA_1',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'provincias_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'provincia_apertura_2' => 
  array (
    'required' => false,
    'name' => 'provincia_apertura_2',
    'vname' => 'LBL_PROVINCIA_APERTURA_2',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'provincias_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'provincia_apertura_3' => 
  array (
    'required' => false,
    'name' => 'provincia_apertura_3',
    'vname' => 'LBL_PROVINCIA_APERTURA_3',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'provincias_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'localidad_apertura_1' => 
  array (
    'required' => false,
    'name' => 'localidad_apertura_1',
    'vname' => 'LBL_LOCALIDAD_APERTURA_1',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'municipios_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'localidad_apertura_2' => 
  array (
    'required' => false,
    'name' => 'localidad_apertura_2',
    'vname' => 'LBL_LOCALIDAD_APERTURA_2',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'municipios_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'localidad_apertura_3' => 
  array (
    'required' => false,
    'name' => 'localidad_apertura_3',
    'vname' => 'LBL_LOCALIDAD_APERTURA_3',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'municipios_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'observaciones_zona_apertura' => 
  array (
    'required' => false,
    'name' => 'observaciones_zona_apertura',
    'vname' => 'LBL_OBSERVACIONES_ZONA_APERTURA',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '60',
  ),
  
 'tipo_origen' => 
  array (
    'required' => true,
    'name' => 'tipo_origen',
    'vname' => 'LBL_TIPO_ORIGEN',
    'type' => 'multienum',
    'massupdate' => 1,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'tipo_origen_list',
    'isMultiSelect' => 1, 
    'studio' => 'visible',
    'dependency' => false,
  ),
  'empresa' => 
  array (
    'required' => false,
    'name' => 'empresa',
    'vname' => 'LBL_EMPRESA',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'fecha_primer_contacto' => 
  array (
    'required' => false,
    'name' => 'fecha_primer_contacto',
    'vname' => 'LBL_FECHA_PRIMER_CONTACTO',
    'type' => 'date',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  'last_name' => 
  array (
    'name' => 'last_name',
    'vname' => 'LBL_LAST_NAME',
    'type' => 'varchar',
    'len' => '100',
    'unified_search' => true,
    'full_text_search' => 
    array (
      'boost' => 3,
    ),
    'comment' => 'Last name of the contact',
    'merge_filter' => 'disabled',
    'required' => false,
    'importable' => 'required',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Last name of the contact',
    'help' => '',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'size' => '20',
  ),
  'contacto_secundario' => 
  array (
    'required' => false,
    'name' => 'contacto_secundario',
    'vname' => 'LBL_CONTACTO_SECUNDARIO',
    'type' => 'varchar',
    'full_text_search' => 
    array (
      'boost' => 3,
    ),
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => true,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'correo_secundario' => 
  array (
    'required' => false,
    'name' => 'correo_secundario',
    'vname' => 'LBL_CORREO_SECUNDARIO',
    'type' => 'varchar',
    'massupdate' => 0,
    'full_text_search' => 
    array (
      'boost' => 3,
    ),
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => true,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'envio_documentacion' => 
  array (
    'required' => false,
    'name' => 'envio_documentacion',
    'vname' => 'LBL_ENVIO_DOCUMENTACION',
    'type' => 'date',
    'massupdate' => '1',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'enable_range_search' => false,
  ),
  'parent_name' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'parent_name',
    'vname' => 'origen',
    'type' => 'parent',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 25,
    'size' => '20',
    'options' => 'parent_type_display',
    'studio' => 'visible',
    'type_name' => 'parent_type',
    'id_name' => 'parent_id',
    'parent_type' => 'record_type_display',
  ),
  'parent_type' => 
  array (
    'required' => false,
    'name' => 'parent_type',
    'vname' => 'LBL_PARENT_TYPE',
    'type' => 'parent_type',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 255,
    'size' => '20',
    'dbType' => 'varchar',
    'studio' => 'hidden',
  ),
  'parent_id' => 
  array (
    'required' => false,
    'name' => 'parent_id',
    'vname' => 'LBL_PARENT_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'enviar_servicios_asesora' => 
  array (
    'required' => false,
    'name' => 'enviar_servicios_asesora',
    'vname' => 'LBL_ENVIAR_SERVICIOS_ASESORA',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'date_entered' => 
  array (
    'name' => 'date_entered',
    'vname' => 'LBL_DATE_ENTERED',
    'type' => 'datetime',
    'group' => 'created_by_name',
    'comment' => 'Date record created',
    'enable_range_search' => false,
    'options' => 'date_range_search_dom',
    'required' => false,
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Date record created',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'dbType' => 'datetime',
    'display_default' => 'now',
  ),
  
  'expan_evento_id_c' => 
  array (
    'required' => false,
    'name' => 'expan_evento_id_c',
    'vname' => 'LBL_EVENTO',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'eventos_list',
    'studio' => 'visible',
    'dependency' => false,
  ), 

  'portal' => 
  array (
    'required' => false,
    'name' => 'portal',
    'vname' => 'LBL_PORTAL',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'portal_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
    'subor_medios' => 
  array (
    'required' => false,
    'name' => 'subor_medios',
    'vname' => 'LBL_SUBOR_MEDIOS',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'subor_medios_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
      'subor_central' => 
  array (
    'required' => false,
    'name' => 'subor_central',
    'vname' => 'LBL_SUBOR_CENTRAL',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'subor_central_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'subor_expande' => 
  array (
    'required' => false,
    'name' => 'subor_expande',
    'vname' => 'LBL_SUBOR_EXPANDE',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'subor_expande_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'subor_mailing' => 
  array (
    'required' => false,
    'name' => 'subor_mailing',
    'vname' => 'LBL_SUBOR_MAILING',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'subor_mailing_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'expan_franquicia_id_c' => 
  array (
    'required' => false,
    'name' => 'expan_franquicia_id_c',
    'vname' => 'LBL_FRANQUICIA_TEMP_EXPAN_FRANQUICIA_ID',
    'type' => 'id',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => true,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 36,
    'size' => '20',
  ),
  'franquicia_temp' => 
  array (
    'required' => true,
    'source' => 'non-db',
    'name' => 'franquicia_temp',
    'vname' => 'LBL_FRANQUICIA_TEMP',
    'type' => 'relate',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'id_name' => 'expan_franquicia_id_c',
    'ext2' => 'Expan_Franquicia',
    'module' => 'Expan_Franquicia',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
  
  'franquicias_contactadas' => 
  array (
    'required' => false,
    'name' => 'franquicias_contactadas',
    'vname' => 'LBL_FRANQUICIAS_CONTACTADAS',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'popupHelp'=>'Se pueden añadir varias franquicias separadas por coma',
  ),
  
  'phone_work' => 
  array (
    'name' => 'phone_work',
    'vname' => 'LBL_OFFICE_PHONE',
    'type' => 'phone',
    'dbType' => 'varchar',
    'len' => '100',
    'audited' => true,
    'unified_search' => true,
    'full_text_search' => 
    array (
      'boost' => 1,
    ),
    'comment' => 'Work phone number of the contact',
    'merge_filter' => 'disabled',
    'required' => false,
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Work phone number of the contact',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'reportable' => true,
    'size' => '20',
  ),
  
  'phone_other' => 
  array (
    'name' => 'phone_other',
    'vname' => 'LBL_OTHER_PHONE',
    'type' => 'phone',
    'dbType' => 'varchar',
    'len' => '100',
    'unified_search' => true,
    'full_text_search' => 
    array (
      'boost' => 1,
    ),
    'comment' => 'Other phone number for the contact',
    'merge_filter' => 'disabled',
    'required' => false,
    'massupdate' => 0,
    'no_default' => false,
    'comments' => 'Other phone number for the contact',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'size' => '20',
  ),
  
  'experiencia_sector' => 
  array (
    'required' => false,
    'name' => 'experiencia_sector',
    'vname' => 'LBL_EXPERIENCIA_SECTOR',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
  'desc_experiencia' => 
  array (
    'required' => false,
    'name' => 'desc_experiencia',
    'vname' => 'DESC_EXPERIENCIA',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'abierta' => 
  array (
    'required' => false,
    'name' => 'abierta',
    'vname' => 'LBL_ABIERTA',
    'type' => 'bool',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'espera' => 
  array (
    'required' => false,
    'name' => 'espera',
    'vname' => 'LBL_ESPERA',
    'type' => 'bool',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
    'cerrada' => 
  array (
    'required' => false,
    'name' => 'cerrada',
    'vname' => 'LBL_CERRADA',
    'type' => 'bool',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
    'positiva' => 
  array (
    'required' => false,
    'name' => 'positiva',
    'vname' => 'LBL_POSITIVA',
    'type' => 'bool',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'prioridad' =>
  array (
    'name' => 'prioridad',
    'vname' => 'LBL_PRIORIDAD',
    'type' => 'int',
    'len' => '3',
    'default' => 0,
    'audited' => true,
    'reportable' => false,
    'unified_search' => false,
    'comment' => 'Prioridad de la Solicitud',
  ),      
  'oportunidad_inmediata' => 
  array (
    'required' => false,
    'name' => 'oportunidad_inmediata',
    'vname' => 'LBL_OPORTUNIDAD_INMEDIATA',
    'type' => 'bool',
    'massupdate' => 1,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'size' => '10',
  ),
  
   'disp_contacto' => 
  array (
    'required' => false,
    'name' => 'disp_contacto',
    'vname' => 'LBL_DISPONIBILIDAD_HORARIA_CONTACTO',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'disponibilidad_horaria_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
    'skype' => 
  array (
    'required' => false,
    'name' => 'skype',
    'vname' => 'LBL_SKYPE',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => true,
    'merge_filter' => 'disabled',
    'len' => '60',
    'size' => '20',
  ),
  
    'recursos_propios'=>
  array (
    'required' => false,
    'name' => 'recursos_propios',
    'vname' => 'LBL_RECURSOS_PROPIOS',
    'type' => 'enum',
    'massupdate' => '1',
    'no_default' => false,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'recursos_propios_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  
  'dummie' => 
  array (
    'required' => false,
    'name' => 'dummie',
    'vname' => 'dummie',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
  'suborigen'=>
  array(
      'name' => 'suborigen',
      'vname' => 'LBL_SUBORIGEN',
      'type' => 'varchar',
      'len' => '255',
      'default'=>'Hola',
      'source' => 'non-db',
  ),
  
  
  'master' => 
  array (
    'required' => false,
    'name' => 'master',
    'vname' => 'LBL_MASTER_FRANQUICIA',
    'type' => 'bool',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  'provincia_residencia' => 
  array (
    'required' => false,
    'name' => 'provincia_residencia',
    'vname' => 'LBL_PROVINCIA_RESIDENCIA',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'provinciasInternacional_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
  'localidad_residencia' => 
  array (
    'required' => false,
    'name' => 'localidad_residencia',
    'vname' => 'LBL_LOCALIDAD_RESIDENCIA',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
    
  'no_newsletter' => 
  array (
    'required' => false,
    'name' => 'no_newsletter',
    'vname' => 'LBL_NEWSLETTER',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
  'check_puertas_abiertas' => 
  array (
    'required' => false,
    'name' => 'check_puertas_abiertas',
    'vname' => 'LBL_PUERTAS_ABIERTAS',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
  'tags_empresa' => 
  array (
    'required' => false,
    'name' => 'tags_empresa',
    'vname' => 'LBL_TAG_EMPRESA',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '512',
    'size' => '100',
    'popupHelp'=>'Se pueden añadir varias franquicias separadas por coma',
  ),
  
  'habilidades' => 
  array (
    'required' => false,
    'name' => 'habilidades',
    'vname' => 'LBL_HABILIDADES',
    'type' => 'multienum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'lst_habilidades',
    'studio' => 'visible',
    'isMultiSelect' => true,
    'default' => '^^',
  ),
  
  'situacion_personal' => 
  array (
    'required' => false,
    'name' => 'situacion_personal',
    'vname' => 'LBL_SITUACION_PERSONAL',
    'type' => 'multienum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'lst_situacion_personal',
    'studio' => 'visible',
    'isMultiSelect' => true,
    'default' => '^^',
  ),
  
  'motivos_interes' => 
  array (
    'required' => false,
    'name' => 'motivos_interes',
    'vname' => 'LBL_MOTIVOS_INTERES',
    'type' => 'multienum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'lst_motivos_interes',
    'studio' => 'visible',
    'isMultiSelect' => true,
    'default' => '^^',
  ),
  
  'historial_empresa' => 
  array (
    'required' => false,
    'name' => 'historial_empresa',
    'vname' => 'LBL_HISTORIAL_EMPRESA',
    'type' => 'multienum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'lst_historial_empresa',
    'studio' => 'visible',
    'isMultiSelect' => true,
    'default' => '^^',
  ),
  
  'from_import' => 
  array (
    'required' => false,
    'name' => 'from_import',
    'vname' => 'LBL_FROM_IMPORT',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
  ),
  
  'otros_sectores' => 
  array (
    'required' => false,
    'name' => 'otros_sectores',
    'vname' => 'LBL_OTROS_SECTORES',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '10',
    'studio' => 'visible',
    'rows' => '2',
    'cols' => '60',    
  ),
  
  'linkedin' => 
  array (
    'required' => false,
    'name' => 'linkedin',
    'vname' => 'LBL_LINKEDIN',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => true,
    'merge_filter' => 'disabled',
    'len' => '60',
    'size' => '20',
  ),
  
  'rrss' => 
  array (
    'required' => false,
    'name' => 'rrss',
    'vname' => 'LBL_RRSS',
    'type' => 'text',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '64',
    
  ),
  
  'delegado' => 
  array (
    'required' => false,
    'name' => 'delegado',
    'vname' => 'LBL_DELEGADO',
    'type' => 'enum',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'size' => '20',
    'options' => 'lst_tipo_delegado',
    'studio' => 'visible',
  ),   
  
  'sectores_historicos' => 
  array (
    'required' => false,
    'name' => 'sectores_historicos',
    'vname' => 'LBL_SECTORES_HISTORICOS',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'popupHelp'=>'Se pueden añadir varios sectores separados por coma',
  ),  
  
  'franquicia_historicos' => 
  array (
    'required' => false,
    'name' => 'franquicia_historicos',
    'vname' => 'LBL_FRANQUICIA_HISTORICOS',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'popupHelp'=>'Se pueden añadir varias franquicias separadas por coma',
  ),
  
  'empresa_temp' => 
  array (    
    'source' => 'non-db',
    'name' => 'empresa_temp',
    'vname' => 'LBL_EMPRESA_TEMP',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
  'inicio_franq_hst' => 
  array (
    'required' => false,
    'name' => 'inicio_franq_hst',
    'vname' => 'LBL_FRANQUICIA_INICIO',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '20',
    'size' => '5',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => 0,
    'max' => false,
    'validation' => 
    array (
      'type' => 'range',
      'min' => 0,
      'max' => false,
    ),
  ),
  
  'fin_franq_hst' => 
  array (
    'required' => false,
    'name' => 'fin_franq_hst',
    'vname' => 'LBL_FRANQUICIA_CIERRE',
    'type' => 'int',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '20',
    'size' => '5',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => 0,
    'max' => false,
    'validation' => 
    array (
      'type' => 'range',
      'min' => 0,
      'max' => false,
    ),
  ),
  
  'chk_empresa_provee' => 
  array (
    'required' => false,
    'name' => 'chk_empresa_provee',
    'vname' => 'LBL_EMPRESA_PROVEE',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'popupHelp' => 'La empresa es proveedor',    
  ),
  
  'chk_empresa_cli_potencial' => 
  array (
    'required' => false,
    'name' => 'chk_empresa_cli_potencial',
    'vname' => 'LBL_EMPRESA_CLI_POTENCIAL',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'popupHelp' => 'La empresa es un cliente potencial',    
  ),
  
  'chk_empresa_competencia' => 
  array (
    'required' => false,
    'name' => 'chk_empresa_competencia',
    'vname' => 'LBL_EMPRESA_COMPETENCIA',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'popupHelp' => 'La empresa es competencia de nuestras franquicias',    
  ),
  
  'chk_empresa_alianza' => 
  array (
    'required' => false,
    'name' => 'chk_empresa_alianza',
    'vname' => 'LBL_EMPRESA_ALIANZA',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
    'popupHelp' => 'La empresa puede ser una alianza',    
  ),
  
  
  'franquicia_satisfa' => 
  array (
    'required' => false,
    'name' => 'franquicia_satisfa',
    'vname' => 'LBL_FRANQUICIA_SATISFA',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'auto',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => 100,
    'size' => '20',
    'options' => 'satisfa_fran_list',
    'studio' => 'visible',
    'dependency' => false,
  ),   
  
  'chk_entrevista_previa_EN' => 
  array (
    'required' => false,
    'name' => 'chk_entrevista_previa_EN',
    'vname' => 'LBL_ENTREVISTA_PREVIA_EN',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
  'f_entrevista_previa_EN' => 
  array (
    'required' => false,
    'name' => 'f_entrevista_previa_EN',
    'vname' => 'LBL_FECHA_ENTREVISTA_PREVIA_EN',
    'type' => 'date',
    'massupdate' => '1',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'enable_range_search' => false,
  ),
  
  'usuario_entrevista_previa_EN' => 
  array (
    'required' => false,
    'name' => 'usuario_entrevista_previa_EN',
    'vname' => 'LBL_USUARIO_ENTREVISTA_PREVIA_EN',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
    
  'chk_entrevista_previa_cliente' => 
  array (
    'required' => false,
    'name' => 'chk_entrevista_previa_cliente',
    'vname' => 'LBL_ENTREVISTA_PREVIA_CLIENTE',
    'type' => 'bool',
    'massupdate' => 0,
    'default' => '0',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
  'f_entrevista_previa_cliente' => 
  array (
    'required' => false,
    'name' => 'f_entrevista_previa_cliente',
    'vname' => 'LBL_FECHA_ENTREVISTA_PREVIA_CLIENTE',
    'type' => 'date',
    'massupdate' => '1',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'enable_range_search' => false,
  ),
  
  'usuario_entrevista_previa_cliente' => 
  array (
    'required' => false,
    'name' => 'usuario_entrevista_previa_cliente',
    'vname' => 'LBL_USUARIO_ENTREVISTA_PREVIA_CLIENTE',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'len' => '255',
    'size' => '20',
  ),
  
),
	'relationships'=>array (
),
	'optimistic_locking'=>true,
		'unified_search'=>true,
	);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('Expan_Solicitud','Expan_Solicitud', array('basic','assignable','person'));